### ISSUE TITLE
Bootloop with D855 30B MM Stock rom

### ISSUE THREAD

**Issue by pikachukaki** [rovo89/Xposed#111] opened 2016-01-02 02:32 UTC
Some say the rom need to be deodexed....im not sure this is the logcat

[logcat.txt](https://github.com/rovo89/Xposed/files/76115/logcat.txt)

**Comment by pikachukaki** [comment] 2016-01-02 02:43
And another logcat with some new Errors
[logcat.txt](https://github.com/rovo89/Xposed/files/76118/logcat.txt)

**Comment by suljo94** [comment] 2016-01-09 05:04
so pickatchkaki was partially wright, the rom boots with xposed (sometimes) but sometimes it just loops for ever(half of the power ups). besides that there is another issue when the phone boots it still gives the android is updating message with under that the message that apps are being started(it happens every time)

I put both the logs in the dropbox folder and named the logs according to the problem
https://www.dropbox.com/sh/e7vn0s0ijzdleqk/AAA1H5YWHAAzeUmIpsdV4HnRa?dl=0

**Comment by xXCooL69GuYXx** [comment] 2016-01-09 05:10
What is this ?

**Comment by suljo94** [comment] 2016-01-09 05:22
explaination and logs of lg g3 issues with xposed? are you missing data or do you need something more?

**Comment by xXCooL69GuYXx** [comment] 2016-01-09 05:37
Ill send a picture and i have a lg g4. H81110n on t mobile

**Comment by rovo89** [comment] 2016-01-20 21:22
Duplicate of #100.

**Closed by rovo89** 2016-01-20 21:22 UTC
