### ISSUE TITLE
MyAndroidTools app can't start after installing xposed v79

### ISSUE THREAD

**Issue by piskor** [rovo89/Xposed#102] opened 2015-12-18 23:20 UTC
Hi rovo89
After installing xposed v79 sdk22 arm on s4 mini lte with cm12.1 based rom I'm not able to launch MyAndroidTools app https://play.google.com/store/apps/details?id=cn.wq.myandroidtools, as described in xda post http://forum.xda-developers.com/xposed/official-xposed-lollipop-t3030118/post64381801#post64381801
On v78 sdk22 arm version it is working without problems
Logcat is attached to xda post http://forum.xda-developers.com/attachment.php?attachmentid=3581391&d=1450473336

Best Regards, piskor

**Comment by piskor** [comment] 2015-12-18 23:47
More info
Xposed log http://pastebin.com/HEQLjymd
and mentioned in xposed log /data/tombstones/tombstone_04 file uploaded to dropbox
https://www.dropbox.com/s/ct4b4f7d62rjacd/tombstone_04?dl=0
Best Regards, piskor

**Comment by tema-borisov** [comment] 2015-12-20 16:24
It looks like I have same issue with other app:
https://play.google.com/store/apps/details?id=ru.yandex.yandexbus
works fine on xposed v78-sdk23-arm64, won't start with v79-sdk23-arm64

Other app from the same developer can't display maps in interface after updating to v79
https://play.google.com/store/apps/details?id=ru.yandex.taxi

This probably means that there are some issue with native libs these apps are using.

I'm on Nexus 6P 6.0.1, stock rom.

**Comment by rovo89** [comment] 2015-12-20 22:36
@piskor I have indeed done a change in the place where it crashes, but I have no idea why it would crash like this... If you notice any other apps with the same issue, please let me know. I can't reproduce this the moment because I have just upgrades my phone to CM13... So maybe I'll need to add some debug logging and send it to you for more information.

@tema-borisov I can reproduce the yandexbus issue also on the Nexus 5 (arm) 6.0.1, but unfortunately, there isn't any clear error message in the log, no real crash. For normal apps, the biggest change between v78 and v79 is that I merged the AOSP changes from 6.0.1. I tried to revert all of these changes and it seemed to work. So can you please test if the apps work on 6.0.1 without Xposed?

**Comment by wanam** [comment] 2015-12-21 09:38
@rovo89 I can reproduce MyAndroidTools issue
Is it caused by this change https://github.com/rovo89/android_art/commit/037e5225c031f994278209e9aff76d5607645de0 ? i noticed that you partially merged it from this change https://android-review.googlesource.com/#/c/144761/, any reasons for this?

**Comment by tema-borisov** [comment] 2015-12-21 09:50
@rovo89 Checked yandexbus on friends Nexus 5X 6.0.1 without exposed - it works there.

**Comment by Enyby** [comment] 2015-12-29 15:50
GameGuardian started from version 8.1.0 crashed in boot.oat if Xposed installed.
Link to apk: https://gameguardian.net/forum/files/file/2-gameguardian/
Link to error: https://gameguardian.net/forum/topic/7398-gathering-information-about-gg-errors/?do=findComment&comment=43852
Link to logcat: 
https://gameguardian.net/forum/topic/7398-gathering-information-about-gg-errors/?do=findComment&comment=43851
https://gameguardian.net/forum/topic/7398-gathering-information-about-gg-errors/?do=findComment&comment=43887
Describe problem:
http://forum.xda-developers.com/showpost.php?p=64544001&postcount=2511

**Comment by Enyby** [comment] 2015-12-30 22:09
Another logcat: https://gameguardian.net/forum/topic/7398-gathering-information-about-gg-errors/?do=findComment&comment=43930

**Comment by rovo89** [comment] 2015-12-31 16:41
@wanam That's a prerequisite for https://github.com/rovo89/android_art/commit/7858bc989a8eaa08ec2472109b6f03529540b742. But you see the commit, I have no idea how this could cause the error... As you have a device to reproduce, could you try to add some debug logging to the constructor? Or maybe start by reverting those two commits and see if this is indeed causing the issue? I can't get the app on Genymotion because its native libraries use SSSE3, which isn't supported by my CPU (AMD Phenom II X6 1055T). I'm even thinking about switching to Intel as such incompatibilties occur more often lately and I can't use the official emulator either...

@tema-borisov I'll try to find out more. Anyway, this seems to be a different issue than the original one, so could you please create a new issue here? https://github.com/rovo89/android_art/issues
You can simply copy & paste your initial comment, it's just better to keep track of individual issues.

@Enyby Same for you - please don't hijack this issue and open a new one instead. Closing an issue as a duplicate later is easy, moving comments to a separate issue is not possible on GitHub. Please make sure that the logs are accessible without registering somewhere. Please also share more details how this app works. From its description, it sounds like it modifies the memory and stack of apps. That sounds pretty risky on its own. Are you sure that it doesn't rely on internal data structures of ART? Those might be different when Xposed is installed. Please reply in the new issue, not here.

**Comment by piskor** [comment] 2016-01-01 19:22
@rovo89 There are no other apps with this issue for me. Please prepare framework with more debug logging if you find some free time

**Comment by wanam** [comment] 2016-01-02 11:37
@rovo89 I actually upgraded to the beta TW M on my GS6, i built a new unofficial update with less changes this time, thanks to Samsung for this, it works great with no compilation errors. 

I cannot reproduce this crash anymore, and i cannot also downgrade my gs6 since there are no full TW M Roms yet, so i will try to downgrade my wife's Nexus 6 and try to debug this issue.

**Comment by wanam** [comment] 2016-01-02 17:19
I reverted the two last 2 commits but MyAndroidTools still crashes, but reverting the third one https://github.com/rovo89/android_art/commit/037e5225c031f994278209e9aff76d5607645de0 fixed the issue, so i can confirm that this architectural change is the culprit, 

Maybe because this app native code depends on art internals, it seems to crash on the changed constructor:
```diff
    DexFile(const byte* base, size_t size,
           const std::string& location,
           uint32_t location_checksum,
           MemMap* mem_map,
-          const OatFile* oat_file);
+          const OatDexFile* oat_dex_file);
```
I will try to put some debug infos when i get a free time and report back.

**Comment by rovo89** [comment] 2016-01-24 19:30
I found out that the APK is protected with a Chinese software. See https://github.com/rovo89/XposedBridge/issues/69 why this isn't supported for Xposed modules.

As for running a normal app with this protection: It's crashing because the `location` field contains an invalid reference. I assume that the protection relies on certain internals of ART and these assumptions are broken due to this commit. I have tried various things and what's actually breaking it is the change of the `DexFile::OpenMemory()` signature, even when the value is actually a `nullptr`. Maybe this changes the order of the methods in the compiled library and invalidates a possibly hardcoded offset in the protection library.

**Comment by rovo89** [comment] 2016-01-28 17:07
@piskor (or anyone else with this issue): Could you please try this?
https://www.dropbox.com/s/1gosytfy4eymmzq/xposed-v80-sdk22-arm-test3.zip?dl=0

**Comment by piskor** [comment] 2016-01-28 19:26
@rovo89 I'm on CM13 based ROM at the moment. I will try it on weekend. Thank You

**Comment by rovo89** [comment] 2016-02-01 19:35
@piskor Did you find the time to test this?

**Comment by wanam** [comment] 2016-02-01 21:36
Tested the app with test3 successfully on a Nexus 5 running stock 5.1.1.

Thank you.

**Comment by rovo89** [comment] 2016-02-02 17:32
Thanks for testing!

**Comment by rovo89** [comment] 2016-02-02 18:16
Fixed in v80.

**Closed by rovo89** 2016-02-02 18:16 UTC

**Comment by piskor** [comment] 2016-02-02 18:23
@rovo89 Thank You very much. Tested it today. App works without issues. Sorry for late reply. I was out of home this weekend.

**Comment by Hepolise** [comment] 2016-02-03 07:35
https://play.google.com/store/apps/details?id=ru.yandex.yandexbus
This app is crashing on v80, Android 6.0.1 :(

**Comment by rovo89** [comment] 2016-02-03 08:01
@Hepolise https://github.com/rovo89/android_art/issues/26

**Comment by sn0w89** [comment] 2016-02-03 13:05
hi, have SGS4 i9505, flash with all wipes cm13 03.02, after flash v80, I having same problems like Hepolise, crashing yandex maps and bus. Have this problem with v79 on cm13, but with v78 work fine. on cm12.1 v79 yandex apps works without crashes.

**Comment by rovo89** [comment] 2016-02-03 16:29
@sn0w89 See the comment above yours. I'm locking this issue to prevent further unrelated comments...
