### ISSUE TITLE
LG H410

### ISSUE THREAD

**Issue by Soft-Man** [rovo89/Xposed#92] opened 2015-11-20 06:55 UTC
[error.log.2.txt](https://github.com/rovo89/Xposed/files/39809/error.log.2.txt)

**Comment by Soft-Man** [comment] 2015-11-20 15:40
the source code of the firmware files. maybe it will help in solving the problem.
https://drive.google.com/a/citymasseurs.ru/file/d/0B2QhEXa2ySgkX21kZzl0TC1FQlU/view

**Comment by rovo89** [comment] 2015-11-29 20:33
Could you try this please? https://www.dropbox.com/s/pwxgrwnqm6howh7/xposed-v79-sdk22-arm-test.zip?dl=0

**Comment by Soft-Man** [comment] 2015-11-29 23:35
[error.log.txt](https://github.com/rovo89/Xposed/files/46797/error.log.txt)

**Comment by rovo89** [comment] 2015-11-30 05:49
Too bad that it still crashes. I will probably need some files of your ROM to reproduce this. To find out which ones are affected, please send me a full logcat of the same procedure. Start "adb logcat -v time > logcat.txt" As soon as possible after turning on the device, wait until the crash happens and then press Ctrl+C.

**Comment by Soft-Man** [comment] 2015-11-30 06:24
[logcat.txt](https://github.com/rovo89/Xposed/files/46985/logcat.txt)

**Comment by Soft-Man** [comment] 2015-11-30 06:41
system.img - https://drive.google.com/file/d/0B2QhEXa2ySgkSmcwOGFsNGNvZms/view?usp=sharing

**Comment by rovo89** [comment] 2015-12-01 18:11
Unfortunately the logcat starts a little bit too late, I don't see the ROM compiling. Did you clear the Dalvik cache before taking the logcat? Anyway, I extracted some files from your ROM and tried to recompile them. That didn't work for LGTeleService.odex, which fits to the issue you experienced.

I need to do some further analysis. I already know that it fails to resolve some classes which are placed in other jars, but that might be due to different environment. Could you please post the content of /init.environ.rc, or simply zip up all the /init.* files?

**Comment by rovo89** [comment] 2015-12-01 22:01
I'm still interested in the files I mentioned above, but I might have found a solution. Please try this: https://www.dropbox.com/s/3e4w6gopaiz1wdn/xposed-v79-sdk22-arm-test2.zip?dl=0

**Comment by Soft-Man** [comment] 2015-12-02 01:45
all the /init.* files - https://drive.google.com/file/d/0B2QhEXa2ySgkdXl5aTZPNU9PUGc/view?usp=sharing

**Comment by Soft-Man** [comment] 2015-12-02 02:21
sorry for the bad logcat last time.
I tried xposed-v79-sdk22-arm-test2.zip
 Now error сom.android.phone do not have,  but now the Services Google Play stopped and com.android.settings stopped - https://drive.google.com/file/d/0B2QhEXa2ySgkWmY4eFAzNnA0WDg/view?usp=sharing
[xposed.error.log.txt](https://github.com/rovo89/Xposed/files/49319/xposed.error.log.txt)
[logcat.txt](https://github.com/rovo89/Xposed/files/49321/logcat.txt)
I hope right now full logcat made

**Comment by rovo89** [comment] 2015-12-02 19:26
Another attempt: https://www.dropbox.com/s/ii7hldpjhv05zjm/xposed-v79-sdk22-arm-test3.zip?dl=0

**Comment by Soft-Man** [comment] 2015-12-02 20:20
everything seems to be good
[logcat.txt](https://github.com/rovo89/Xposed/files/50147/logcat.txt)
[xposed.error.log.txt](https://github.com/rovo89/Xposed/files/50148/xposed.error.log.txt)
![img-20151202-wa0330](https://cloud.githubusercontent.com/assets/5754395/11542964/2a111584-994b-11e5-8960-41b4aecccbbb.jpg)

**Comment by Soft-Man** [comment] 2015-12-02 22:49
thank you very much for your hard work

**Comment by rovo89** [comment] 2015-12-17 21:27
Fixed in version 79.

**Closed by rovo89** 2015-12-17 21:27 UTC
