### ISSUE TITLE
Bootloop on SGSIII LTE w/ BlizzPop ROM, Android 5.1.1

### ISSUE THREAD

**Issue by wasdennnoch** [rovo89/Xposed#83] opened 2015-11-12 18:02 UTC
Getting a bootloop with latest version and an older version by romracer.

ROM based on CM12.

Full log:

<pre>
11-12 16:39:01.125 I/Xposed  ( 2020): -----------------
11-12 16:39:01.125 I/Xposed  ( 2020): Starting Xposed version 75, compiled for SDK 22
11-12 16:39:01.125 I/Xposed  ( 2020): Device: GT-I9305 (samsung), Android version 5.1.1 (SDK 22)
11-12 16:39:01.125 I/Xposed  ( 2020): ROM: bliss_i9305-rodman01 5.1.1 LMY48W
11-12 16:39:01.125 I/Xposed  ( 2020): Build fingerprint: samsung/m3xx/m3:5.1/LMY470/1767468:user/release-keys
11-12 16:39:01.125 I/Xposed  ( 2020): Platform: armeabi-v7a, 32-bit binary, system server: yes
11-12 16:39:01.125 I/Xposed  ( 2020): SELinux enabled: yes, enforcing: no
11-12 16:39:03.980 I/Xposed  ( 2020): -----------------
11-12 16:39:03.980 I/Xposed  ( 2020): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
11-12 16:39:04.165 I/Xposed  ( 2020): Forcing image recompilation because /data/dalvik-cache/arm/system@framework@boot.art is not compiled for the current Xposed version
11-12 16:39:18.605 F/libc    ( 2404): Fatal signal 6 (SIGABRT), code -6 in tid 2410 (Compiler driver)
11-12 16:39:18.605 I/DEBUG   ( 2005): property debug.db.uid not set; NOT waiting for gdb.
11-12 16:39:18.605 I/DEBUG   ( 2005): HINT: adb shell setprop debug.db.uid 100000
11-12 16:39:18.605 I/DEBUG   ( 2005): HINT: adb forward tcp:5039 tcp:5039
11-12 16:39:18.715 I/DEBUG   ( 2005): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-12 16:39:18.715 I/DEBUG   ( 2005): Build fingerprint: 'samsung/m3xx/m3:5.1/LMY470/1767468:user/release-keys'
11-12 16:39:18.715 I/DEBUG   ( 2005): Revision: '2'
11-12 16:39:18.715 I/DEBUG   ( 2005): ABI: 'arm'
11-12 16:39:18.715 I/DEBUG   ( 2005): pid: 2404, tid: 2410, name: Compiler driver  >>> /system/bin/dex2oat <<<
11-12 16:39:18.715 I/DEBUG   ( 2005): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
11-12 16:39:18.765 I/DEBUG   ( 2005): Abort message: 'art/compiler/dex/ssa_transformation.cc:444] Incompatible set properties'
11-12 16:39:18.765 I/DEBUG   ( 2005):     r0 00000000  r1 0000096a  r2 00000006  r3 00000000
11-12 16:39:18.765 I/DEBUG   ( 2005):     r4 49c1edd8  r5 00000006  r6 00000002  r7 0000010c
11-12 16:39:18.765 I/DEBUG   ( 2005):     r8 0000001b  r9 41e28d60  sl 400d40b8  fp 4a063528
11-12 16:39:18.765 I/DEBUG   ( 2005):     ip 0000096a  sp 49c1e770  lr 401ace4d  pc 401d3000  cpsr 600f0010
11-12 16:39:18.765 I/DEBUG   ( 2005): 
11-12 16:39:18.765 I/DEBUG   ( 2005): backtrace:
11-12 16:39:18.765 I/DEBUG   ( 2005):     #00 pc 0003a000  /system/lib/libc.so (tgkill+12)
11-12 16:39:18.765 I/DEBUG   ( 2005):     #01 pc 00013e49  /system/lib/libc.so (pthread_kill+52)
11-12 16:39:18.765 I/DEBUG   ( 2005):     #02 pc 00014bab  /system/lib/libc.so (raise+10)
11-12 16:39:18.765 I/DEBUG   ( 2005):     #03 pc 000112f5  /system/lib/libc.so (__libc_android_abort+36)
11-12 16:39:18.765 I/DEBUG   ( 2005):     #04 pc 0000f78c  /system/lib/libc.so (abort+4)
11-12 16:39:18.765 I/DEBUG   ( 2005):     #05 pc 0021b3dd  /system/lib/libart.so (art::Runtime::Abort()+160)
11-12 16:39:18.765 I/DEBUG   ( 2005):     #06 pc 000a8277  /system/lib/libart.so (art::LogMessage::~LogMessage()+1066)
11-12 16:39:18.765 I/DEBUG   ( 2005):     #07 pc 0013bdbf  /system/lib/libart-compiler.so (art::MIRGraph::ComputeSuccLineIn(art::ArenaBitVector*, art::ArenaBitVector const*, art::ArenaBitVector const*)+66)
11-12 16:39:18.765 I/DEBUG   ( 2005):     #08 pc 0013be7b  /system/lib/libart-compiler.so (art::MIRGraph::ComputeBlockLiveIns(art::BasicBlock*)+98)
11-12 16:39:18.765 I/DEBUG   ( 2005):     #09 pc 0013c06b  /system/lib/libart-compiler.so (art::MIRGraph::InsertPhiNodes()+186)
11-12 16:39:18.765 I/DEBUG   ( 2005):     #10 pc 0012c9bb  /system/lib/libart-compiler.so
11-12 16:39:18.765 I/DEBUG   ( 2005):     #11 pc 00134ed1  /system/lib/libart-compiler.so
11-12 16:39:18.765 I/DEBUG   ( 2005):     #12 pc 00130735  /system/lib/libart-compiler.so (art::MIRGraph::CalculateBasicBlockInformation()+208)
11-12 16:39:18.765 I/DEBUG   ( 2005):     #13 pc 0012cf9d  /system/lib/libart-compiler.so
11-12 16:39:18.765 I/DEBUG   ( 2005):     #14 pc 0012ea5b  /system/lib/libart-compiler.so
11-12 16:39:18.765 I/DEBUG   ( 2005):     #15 pc 0012ef33  /system/lib/libart-compiler.so (ArtQuickCompileMethod+38)
11-12 16:39:18.765 I/DEBUG   ( 2005):     #16 pc 00145e33  /system/lib/libart-compiler.so (art::CompilerDriver::CompileMethod(art::DexFile::CodeItem const*, unsigned int, art::InvokeType, unsigned short, unsigned int, _jobject*, art::DexFile const&, art::DexToDexCompilationLevel, bool)+1018)
11-12 16:39:18.765 I/DEBUG   ( 2005):     #17 pc 0014662d  /system/lib/libart-compiler.so (art::CompilerDriver::CompileClass(art::ParallelCompilationManager const*, unsigned int)+1528)
11-12 16:39:18.765 I/DEBUG   ( 2005):     #18 pc 0013c931  /system/lib/libart-compiler.so
11-12 16:39:18.765 I/DEBUG   ( 2005):     #19 pc 00234f0b  /system/lib/libart.so (art::ThreadPoolWorker::Run()+34)
11-12 16:39:18.765 I/DEBUG   ( 2005):     #20 pc 00235759  /system/lib/libart.so (art::ThreadPoolWorker::Callback(void*)+52)
11-12 16:39:18.765 I/DEBUG   ( 2005):     #21 pc 00013637  /system/lib/libc.so (__pthread_start(void*)+30)
11-12 16:39:18.765 I/DEBUG   ( 2005):     #22 pc 0001165f  /system/lib/libc.so (__start_thread+6)
11-12 16:39:18.965 I/DEBUG   ( 2005): 
11-12 16:39:18.965 I/DEBUG   ( 2005): Tombstone written to: /data/tombstones/tombstone_08
11-12 16:39:19.395 I/Xposed  ( 2020): Detected ART runtime
11-12 16:39:19.395 I/Xposed  ( 2020): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
11-12 16:39:20.440 E/Xposed  ( 2020): Cannot load any modules because /data/data/de.robv.android.xposed.installer/conf/modules.list was not found
11-12 16:39:34.250 F/libc    ( 2637): Fatal signal 6 (SIGABRT), code -6 in tid 2637 (main)
11-12 16:39:34.250 I/DEBUG   ( 2005): property debug.db.uid not set; NOT waiting for gdb.
11-12 16:39:34.250 I/DEBUG   ( 2005): HINT: adb shell setprop debug.db.uid 100000
11-12 16:39:34.250 I/DEBUG   ( 2005): HINT: adb forward tcp:5039 tcp:5039
11-12 16:39:34.350 I/DEBUG   ( 2005): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-12 16:39:34.350 I/DEBUG   ( 2005): Build fingerprint: 'samsung/m3xx/m3:5.1/LMY470/1767468:user/release-keys'
11-12 16:39:34.350 I/DEBUG   ( 2005): Revision: '2'
11-12 16:39:34.350 I/DEBUG   ( 2005): ABI: 'arm'
11-12 16:39:34.350 I/DEBUG   ( 2005): pid: 2637, tid: 2637, name: main  >>> /system/bin/dex2oat <<<
11-12 16:39:34.350 I/DEBUG   ( 2005): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
11-12 16:39:34.390 I/DEBUG   ( 2005): Abort message: 'art/runtime/runtime.cc:841] Check failed: options->boot_class_path_->size() != 0U (options->boot_class_path_->size()=0, 0U=0) '
11-12 16:39:34.390 I/DEBUG   ( 2005):     r0 00000000  r1 00000a4d  r2 00000006  r3 00000000
11-12 16:39:34.390 I/DEBUG   ( 2005):     r4 4015ee38  r5 00000006  r6 00000002  r7 0000010c
11-12 16:39:34.390 I/DEBUG   ( 2005):     r8 00000062  r9 40f13d60  sl 400049e8  fp 40007490
11-12 16:39:34.390 I/DEBUG   ( 2005):     ip 00000a4d  sp bee1b020  lr 401b4e4d  pc 401db000  cpsr 60070010
11-12 16:39:34.390 I/DEBUG   ( 2005): 
11-12 16:39:34.390 I/DEBUG   ( 2005): backtrace:
11-12 16:39:34.390 I/DEBUG   ( 2005):     #00 pc 0003a000  /system/lib/libc.so (tgkill+12)
11-12 16:39:34.390 I/DEBUG   ( 2005):     #01 pc 00013e49  /system/lib/libc.so (pthread_kill+52)
11-12 16:39:34.390 I/DEBUG   ( 2005):     #02 pc 00014bab  /system/lib/libc.so (raise+10)
11-12 16:39:34.390 I/DEBUG   ( 2005):     #03 pc 000112f5  /system/lib/libc.so (__libc_android_abort+36)
11-12 16:39:34.390 I/DEBUG   ( 2005):     #04 pc 0000f78c  /system/lib/libc.so (abort+4)
11-12 16:39:34.390 I/DEBUG   ( 2005):     #05 pc 0021b3dd  /system/lib/libart.so (art::Runtime::Abort()+160)
11-12 16:39:34.390 I/DEBUG   ( 2005):     #06 pc 000a8277  /system/lib/libart.so (art::LogMessage::~LogMessage()+1066)
11-12 16:39:34.390 I/DEBUG   ( 2005):     #07 pc 0021daf3  /system/lib/libart.so (art::Runtime::Init(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void const*>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void const*> > > const&, bool)+5110)
11-12 16:39:34.390 I/DEBUG   ( 2005):     #08 pc 0021e69b  /system/lib/libart.so (art::Runtime::Create(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void const*>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void const*> > > const&, bool)+46)
11-12 16:39:34.390 I/DEBUG   ( 2005):     #09 pc 000096f3  /system/bin/dex2oat
11-12 16:39:34.390 I/DEBUG   ( 2005):     #10 pc 0000d0fb  /system/bin/dex2oat
11-12 16:39:34.390 I/DEBUG   ( 2005):     #11 pc 0000f649  /system/lib/libc.so (__libc_init+44)
11-12 16:39:34.390 I/DEBUG   ( 2005):     #12 pc 00004cd8  /system/bin/dex2oat
11-12 16:39:34.465 I/DEBUG   ( 2005): 
11-12 16:39:34.465 I/DEBUG   ( 2005): Tombstone written to: /data/tombstones/tombstone_09
11-12 16:39:34.565 F/libc    ( 2639): Fatal signal 6 (SIGABRT), code -6 in tid 2639 (main)
11-12 16:39:34.565 I/DEBUG   ( 2005): property debug.db.uid not set; NOT waiting for gdb.
11-12 16:39:34.565 I/DEBUG   ( 2005): HINT: adb shell setprop debug.db.uid 100000
11-12 16:39:34.565 I/DEBUG   ( 2005): HINT: adb forward tcp:5039 tcp:5039
11-12 16:39:34.670 I/DEBUG   ( 2005): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-12 16:39:34.670 I/DEBUG   ( 2005): Build fingerprint: 'samsung/m3xx/m3:5.1/LMY470/1767468:user/release-keys'
11-12 16:39:34.670 I/DEBUG   ( 2005): Revision: '2'
11-12 16:39:34.670 I/DEBUG   ( 2005): ABI: 'arm'
11-12 16:39:34.670 I/DEBUG   ( 2005): pid: 2639, tid: 2639, name: main  >>> /system/bin/dex2oat <<<
11-12 16:39:34.670 I/DEBUG   ( 2005): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
11-12 16:39:34.705 I/DEBUG   ( 2005): Abort message: 'art/runtime/runtime.cc:841] Check failed: options->boot_class_path_->size() != 0U (options->boot_class_path_->size()=0, 0U=0) '
11-12 16:39:34.705 I/DEBUG   ( 2005):     r0 00000000  r1 00000a4f  r2 00000006  r3 00000000
11-12 16:39:34.705 I/DEBUG   ( 2005):     r4 40156e38  r5 00000006  r6 00000002  r7 0000010c
11-12 16:39:34.705 I/DEBUG   ( 2005):     r8 00000062  r9 41628d60  sl 400001f8  fp 40000c08
11-12 16:39:34.705 I/DEBUG   ( 2005):     ip 00000a4f  sp becd2020  lr 4016be4d  pc 40192000  cpsr 60070010
11-12 16:39:34.705 I/DEBUG   ( 2005): 
11-12 16:39:34.705 I/DEBUG   ( 2005): backtrace:
11-12 16:39:34.705 I/DEBUG   ( 2005):     #00 pc 0003a000  /system/lib/libc.so (tgkill+12)
11-12 16:39:34.705 I/DEBUG   ( 2005):     #01 pc 00013e49  /system/lib/libc.so (pthread_kill+52)
11-12 16:39:34.705 I/DEBUG   ( 2005):     #02 pc 00014bab  /system/lib/libc.so (raise+10)
11-12 16:39:34.705 I/DEBUG   ( 2005):     #03 pc 000112f5  /system/lib/libc.so (__libc_android_abort+36)
11-12 16:39:34.705 I/DEBUG   ( 2005):     #04 pc 0000f78c  /system/lib/libc.so (abort+4)
11-12 16:39:34.705 I/DEBUG   ( 2005):     #05 pc 0021b3dd  /system/lib/libart.so (art::Runtime::Abort()+160)
11-12 16:39:34.705 I/DEBUG   ( 2005):     #06 pc 000a8277  /system/lib/libart.so (art::LogMessage::~LogMessage()+1066)
11-12 16:39:34.705 I/DEBUG   ( 2005):     #07 pc 0021daf3  /system/lib/libart.so (art::Runtime::Init(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void const*>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void const*> > > const&, bool)+5110)
11-12 16:39:34.705 I/DEBUG   ( 2005):     #08 pc 0021e69b  /system/lib/libart.so (art::Runtime::Create(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void const*>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void const*> > > const&, bool)+46)
11-12 16:39:34.705 I/DEBUG   ( 2005):     #09 pc 000096f3  /system/bin/dex2oat
11-12 16:39:34.705 I/DEBUG   ( 2005):     #10 pc 0000d0fb  /system/bin/dex2oat
11-12 16:39:34.705 I/DEBUG   ( 2005):     #11 pc 0000f649  /system/lib/libc.so (__libc_init+44)
11-12 16:39:34.705 I/DEBUG   ( 2005):     #12 pc 00004cd8  /system/bin/dex2oat
11-12 16:39:34.775 I/DEBUG   ( 2005): 
11-12 16:39:34.775 I/DEBUG   ( 2005): Tombstone written to: /data/tombstones/tombstone_00
11-12 16:39:35.120 F/libc    ( 2647): Fatal signal 6 (SIGABRT), code -6 in tid 2647 (main)
11-12 16:39:35.120 I/DEBUG   ( 2005): property debug.db.uid not set; NOT waiting for gdb.
11-12 16:39:35.120 I/DEBUG   ( 2005): HINT: adb shell setprop debug.db.uid 100000
11-12 16:39:35.120 I/DEBUG   ( 2005): HINT: adb forward tcp:5039 tcp:5039
11-12 16:39:35.220 I/DEBUG   ( 2005): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-12 16:39:35.220 I/DEBUG   ( 2005): Build fingerprint: 'samsung/m3xx/m3:5.1/LMY470/1767468:user/release-keys'
11-12 16:39:35.220 I/DEBUG   ( 2005): Revision: '2'
11-12 16:39:35.220 I/DEBUG   ( 2005): ABI: 'arm'
11-12 16:39:35.220 I/DEBUG   ( 2005): pid: 2647, tid: 2647, name: main  >>> /system/bin/dex2oat <<<
11-12 16:39:35.220 I/DEBUG   ( 2005): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
11-12 16:39:35.260 I/DEBUG   ( 2005): Abort message: 'art/runtime/runtime.cc:841] Check failed: options->boot_class_path_->size() != 0U (options->boot_class_path_->size()=0, 0U=0) '
11-12 16:39:35.260 I/DEBUG   ( 2005):     r0 00000000  r1 00000a57  r2 00000006  r3 00000000
11-12 16:39:35.260 I/DEBUG   ( 2005):     r4 40073e38  r5 00000006  r6 00000002  r7 0000010c
11-12 16:39:35.260 I/DEBUG   ( 2005):     r8 00000062  r9 4024edd0  sl 400261f8  fp 40026c08
11-12 16:39:35.260 I/DEBUG   ( 2005):     ip 00000a57  sp be908020  lr 400bfe4d  pc 400e6000  cpsr 60070010
11-12 16:39:35.260 I/DEBUG   ( 2005): 
11-12 16:39:35.260 I/DEBUG   ( 2005): backtrace:
11-12 16:39:35.260 I/DEBUG   ( 2005):     #00 pc 0003a000  /system/lib/libc.so (tgkill+12)
11-12 16:39:35.260 I/DEBUG   ( 2005):     #01 pc 00013e49  /system/lib/libc.so (pthread_kill+52)
11-12 16:39:35.260 I/DEBUG   ( 2005):     #02 pc 00014bab  /system/lib/libc.so (raise+10)
11-12 16:39:35.260 I/DEBUG   ( 2005):     #03 pc 000112f5  /system/lib/libc.so (__libc_android_abort+36)
11-12 16:39:35.260 I/DEBUG   ( 2005):     #04 pc 0000f78c  /system/lib/libc.so (abort+4)
11-12 16:39:35.260 I/DEBUG   ( 2005):     #05 pc 0021b3dd  /system/lib/libart.so (art::Runtime::Abort()+160)
11-12 16:39:35.260 I/DEBUG   ( 2005):     #06 pc 000a8277  /system/lib/libart.so (art::LogMessage::~LogMessage()+1066)
11-12 16:39:35.260 I/DEBUG   ( 2005):     #07 pc 0021daf3  /system/lib/libart.so (art::Runtime::Init(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void const*>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void const*> > > const&, bool)+5110)
11-12 16:39:35.260 I/DEBUG   ( 2005):     #08 pc 0021e69b  /system/lib/libart.so (art::Runtime::Create(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void const*>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void const*> > > const&, bool)+46)
11-12 16:39:35.260 I/DEBUG   ( 2005):     #09 pc 000096f3  /system/bin/dex2oat
11-12 16:39:35.260 I/DEBUG   ( 2005):     #10 pc 0000d0fb  /system/bin/dex2oat
11-12 16:39:35.260 I/DEBUG   ( 2005):     #11 pc 0000f649  /system/lib/libc.so (__libc_init+44)
11-12 16:39:35.260 I/DEBUG   ( 2005):     #12 pc 00004cd8  /system/bin/dex2oat
11-12 16:39:35.335 I/DEBUG   ( 2005): 
11-12 16:39:35.335 I/DEBUG   ( 2005): Tombstone written to: /data/tombstones/tombstone_01
</pre>

**Comment by rovo89** [comment] 2015-11-15 20:16
Can you please upgrade to version 78 and then get me a full logcat please? "adb logcat -v time > logcat.txt", wait a few minutes, then press Ctrl+C and upload the file. I have seen "Incompatible set properties" errors usually in combination with methods that couldn't be verified.

**Comment by wasdennnoch** [comment] 2015-11-15 20:52
Okay, 20 Minutes should be enough xD

Prepare your ctrl and F key to search 31000 lines

[logcat.txt](https://github.com/rovo89/Xposed/files/35011/logcat.txt)

**Comment by rovo89** [comment] 2015-11-16 16:05
The crashing process is:
`/system/bin/dex2oat --image=/data/dalvik-cache/arm/system@framework@boot.art --dex-file=/system/framework/arm/boot.oat --oat-file=/data/dalvik-cache/arm/system@framework@boot.oat --instruction-set=arm --instruction-set-features=default --base=0x7095b000 --runtime-arg -Xms64m --runtime-arg -Xmx64m --compiler-filter=everything --image-classes=/system/etc/preloaded-classes`

I didn't see log messages regarding failed verification, but I can try to reproduce this if you upload your /system/framework/arm/boot.oat.

**Comment by wasdennnoch** [comment] 2015-11-16 16:25
There it is - uploaded externally, because larger than 10MB: http://www.mediafire.com/download/me6e7ibdrjgxasj/boot.oat

**Comment by rovo89** [comment] 2015-11-17 08:11
Thanks. I can reproduce it. So far, it seems to be caused by a mismatch between codes for special instructions (invoke-virtual-quick). That's not in code I have touched, but the compiler might not expect to see these instructions in AOSP. Maybe the attributes are indeed not maintained properly, at least there are big changes by a commit for Marshmallow: https://android.googlesource.com/platform/art/+/e5f13e57ff8fa36342beb33830b3ec5942a61cca%5E!/#F13

I need more time to check this. As a workaround, please try to change the compiler-filter to something other than "everything". I assume this is configured in /system/build.prop.

**Comment by rovo89** [comment] 2015-11-29 20:34
Could you try this please? https://www.dropbox.com/s/pwxgrwnqm6howh7/xposed-v79-sdk22-arm-test.zip?dl=0

**Comment by wasdennnoch** [comment] 2015-11-29 21:04
It's booting, but the installer says the framework isn't active.

The log says 'Found /data/data/de.robv.android.xposed.installer/conf/disabled, not loading Xposed'

**Comment by rovo89** [comment] 2015-11-29 21:06
Great that it's booting! The message says it all: You seem to have created that file to disable Xposed. Just delete and reboot, then it should work.

**Comment by wasdennnoch** [comment] 2015-11-29 21:10
Afaik I've never created that file, but whatever, It seems to be working now! Thanks for your effort!

**Comment by rovo89** [comment] 2015-11-30 18:54
Well, I have seen flashable ZIPs that create it (to disable Xposed in case of errors) and it would also be created with Xposed's safemode (repeatedly pressing certain keys, might not work on 5.0+ though). Anyway, glad to hear that it works. I'll keep this one open until I have published an official version, I'm still working on a few fixes.

**Comment by rovo89** [comment] 2015-12-17 21:27
Fixed in version 79.

**Closed by rovo89** 2015-12-17 21:27 UTC
