### ISSUE TITLE
Bootloop on LeTV (log provided)

### ISSUE THREAD

**Issue by sansanca** [rovo89/Xposed#50] opened 2015-07-13 16:16 UTC
Xposed not working on this phone. I'm using these files:

XposedInstaller_3.0_alpha4.apk 
xposed-v66-sdk21-arm64.zip
xposed-uninstaller-arm64.zip

First, it bootlooped, the log showed:
Cannot load any modules because /data/data/de.robv.android.xposed.installer/conf/modules.list was not found

So i thought installing Gravitybox for Lollipop, would fill that file. But it gave me the same error, so i manually wrote Gravitybox's apk file location on modules.list And now it shows:

07-10 23:22:19.842 I/Xposed ( 4353): -----------------
07-10 23:22:19.842 I/Xposed ( 4353): Starting Xposed version 66, compiled for SDK 21
07-10 23:22:19.842 I/Xposed ( 4353): Device: X600 (Letv), Android version 5.0.2 (SDK 21)
07-10 23:22:19.842 I/Xposed ( 4353): ROM: ABXCNOP5000306151S release-keys
07-10 23:22:19.842 I/Xposed ( 4353): Build fingerprint: Letv/乐视超级手机1/x600:5.0.2/ABXCNOP5000306151S/48:user/release-keys
07-10 23:22:19.842 I/Xposed ( 4353): Platform: arm64-v8a, 64-bit binary, system server: yes
07-10 23:22:19.842 I/Xposed ( 4353): SELinux enabled: yes, enforcing: yes
07-10 23:22:20.853 I/Xposed ( 4353): -----------------
07-10 23:22:20.853 I/Xposed ( 4353): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
07-10 23:22:21.011 I/Xposed ( 4353): Detected ART runtime
07-10 23:22:21.013 I/Xposed ( 4353): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
07-10 23:22:21.122 I/Xposed ( 4353): Loading modules from /data/app/com.ceco.lollipop.gravitybox-1/base.apk
07-10 23:22:21.276 I/Xposed ( 4353): Loading class com.ceco.lollipop.gravitybox.GravityBox
07-10 23:22:21.287 I/Xposed ( 4353): GB:Hardware: mt6795
07-10 23:22:21.287 I/Xposed ( 4353): GB:Product: 乐视超级手机1
07-10 23:22:21.287 I/Xposed ( 4353): GBevice manufacturer: Letv
07-10 23:22:21.287 I/Xposed ( 4353): GBevice brand: Letv
07-10 23:22:21.287 I/Xposed ( 4353): GBevice model: X600
07-10 23:22:21.290 I/Xposed ( 4353): GBevice type: phone
07-10 23:22:21.290 I/Xposed ( 4353): GB:Is MTK device: true
07-10 23:22:21.290 I/Xposed ( 4353): GB:Is Xperia device: false
07-10 23:22:21.290 I/Xposed ( 4353): GB:Is Moto XT device: false
07-10 23:22:21.291 I/Xposed ( 4353): GB:Has Lenovo custom UI: false
07-10 23:22:21.291 I/Xposed ( 4353): GB:Has telephony support: true
07-10 23:22:21.294 I/Xposed ( 4353): GB:Has Gemini support: true
07-10 23:22:21.294 I/Xposed ( 4353): GB:Android SDK: 21
07-10 23:22:21.294 I/Xposed ( 4353): GB:Android Release: 5.0.2
07-10 23:22:21.294 I/Xposed ( 4353): GB:ROM: ABXCNOP5000306151S release-keys
07-10 23:22:21.329 E/Xposed ( 4353): java.lang.NoSuchMethodError: com.android.internal.telephony.uicc.UiccController #setNotification(int)#exact
07-10 23:22:21.329 E/Xposed ( 4353): at de.robv.android.xposed.XposedHelpers.findMethodExa ct(XposedHelpers.java:181)
07-10 23:22:21.329 E/Xposed ( 4353): at de.robv.android.xposed.XposedHelpers.findAndHookMe thod(XposedHelpers.java:131)
07-10 23:22:21.329 E/Xposed ( 4353): at de.robv.android.xposed.XposedHelpers.findAndHookMe thod(XposedHelpers.java:138)
07-10 23:22:21.329 E/Xposed ( 4353): at com.ceco.lollipop.gravitybox.PhoneWrapper.initZygo te(PhoneWrapper.java:180)
07-10 23:22:21.329 E/Xposed ( 4353): at com.ceco.lollipop.gravitybox.GravityBox.initZygote (GravityBox.java:63)
07-10 23:22:21.329 E/Xposed ( 4353): at de.robv.android.xposed.XposedBridge.loadModule(Xpo sedBridge.java:464)
07-10 23:22:21.329 E/Xposed ( 4353): at de.robv.android.xposed.XposedBridge.loadModules(Xp osedBridge.java:413)
07-10 23:22:21.329 E/Xposed ( 4353): at de.robv.android.xposed.XposedBridge.main(XposedBri dge.java:103)
07-10 23:22:21.385 E/Xposed ( 4353): de.robv.android.xposed.XposedHelpers$ClassNotFound Error: java.lang.ClassNotFoundException: com.mediatek.op.telephony.ServiceStateExt
07-10 23:22:21.385 E/Xposed ( 4353): at de.robv.android.xposed.XposedHelpers.findClass(Xpo sedHelpers.java:54)
07-10 23:22:21.385 E/Xposed ( 4353): at de.robv.android.xposed.XposedHelpers.findAndHookMe thod(XposedHelpers.java:138)
07-10 23:22:21.385 E/Xposed ( 4353): at com.ceco.lollipop.gravitybox.ModTelephony.initZygo te(ModTelephony.java:80)
07-10 23:22:21.385 E/Xposed ( 4353): at com.ceco.lollipop.gravitybox.GravityBox.initZygote (GravityBox.java:67)
07-10 23:22:21.385 E/Xposed ( 4353): at de.robv.android.xposed.XposedBridge.loadModule(Xpo sedBridge.java:464)
07-10 23:22:21.385 E/Xposed ( 4353): at de.robv.android.xposed.XposedBridge.loadModules(Xp osedBridge.java:413)
07-10 23:22:21.385 E/Xposed ( 4353): at de.robv.android.xposed.XposedBridge.main(XposedBri dge.java:103)
07-10 23:22:21.385 E/Xposed ( 4353): Caused by: java.lang.ClassNotFoundException: com.mediatek.op.telephony.ServiceStateExt
07-10 23:22:21.385 E/Xposed ( 4353): at java.lang.Class.classForName(Native Method)
07-10 23:22:21.385 E/Xposed ( 4353): at java.lang.Class.forName(Class.java:308)
07-10 23:22:21.385 E/Xposed ( 4353): at external.org.apache.commons.lang3.ClassUtils.getCl ass(ClassUtils.java:823)
07-10 23:22:21.385 E/Xposed ( 4353): at de.robv.android.xposed.XposedHelpers.findClass(Xpo sedHelpers.java:52)
07-10 23:22:21.385 E/Xposed ( 4353): ... 6 more
07-10 23:22:21.385 E/Xposed ( 4353): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mediatek.op.telephony.ServiceStateExt" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
07-10 23:22:21.385 E/Xposed ( 4353): at dalvik.system.BaseDexClassLoader.findClass(BaseDex ClassLoader.java:56)
07-10 23:22:21.385 E/Xposed ( 4353): at java.lang.ClassLoader.loadClass(ClassLoader.java:5 11)
07-10 23:22:21.385 E/Xposed ( 4353): at java.lang.ClassLoader.loadClass(ClassLoader.java:4 69)
07-10 23:22:21.385 E/Xposed ( 4353): ... 10 more
07-10 23:22:21.385 E/Xposed ( 4353): Suppressed: java.lang.ClassNotFoundException: com.mediatek.op.telephony.ServiceStateExt
07-10 23:22:21.385 E/Xposed ( 4353): at java.lang.Class.classForName(Native Method)
07-10 23:22:21.385 E/Xposed ( 4353): at java.lang.BootClassLoader.findClass(ClassLoader.ja va:781)
07-10 23:22:21.385 E/Xposed ( 4353): at java.lang.BootClassLoader.loadClass(ClassLoader.ja va:841)
07-10 23:22:21.385 E/Xposed ( 4353): at java.lang.ClassLoader.loadClass(ClassLoader.java:5 04)
07-10 23:22:21.385 E/Xposed ( 4353): ... 11 more
07-10 23:22:21.385 E/Xposed ( 4353): Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

This phone is running EUI, a custom UI from LeTV, but i do not think it's heavily customized, but what do i know?... Will xposed only work if this ROM is deodex or something? Anything more i can do to debug/troubleshoot this?

**Comment by rovo89** [comment] 2015-07-14 18:20
> First, it bootlooped, the log showed:
> Cannot load any modules because /data/data/de.robv.android.xposed.installer/conf/modules.list was not found

Did it really bootloop? Or did the device start, but Xposed wasn't working?

> So i thought installing Gravitybox for Lollipop, would fill that file. But it gave me the same error, so i manually wrote Gravitybox's apk file location on modules.list

You shouldn't need to do that. Did you activate the module in Xposed Installer after installing it, and wait a few seconds before rebooting?

The errors in the log are from GravityBox, which might not be compatible with your ROM (version). Sorry, I can't help you with those, you have to check the module support thread.

So the remaining questions are:
- Does the device start or is it hanging in a boot loop?
- Does Xposed Installer report the framework as active?

**Comment by sansanca** [comment] 2015-07-15 02:57
Rovo, actually it just stayed on the logo,, after a few minutes of seing the logo spinning,  it was clear it wasn't going to boot. So i booted in to TWRP and used the uninstaller. And no, the xposed app never showed the framework as active.

Ok, GB is another issue. I think i didn't get the opportunity to activate GB because the framework wasn't active. But on this, is there a way to get more logs that may help troubleshoot this? Via ADB or something?

**Comment by rovo89** [comment] 2015-07-16 06:32
Yes, you could try to execute "adb logcat -v time > logcat.txt" as soon as possible after powering on the device (once you have flashed the framework). Then wait for a few minutes and press Ctrl+C to stop the command.

**Comment by sansanca** [comment] 2015-07-18 03:34
Rovo, my apologies for the delay.It took me a while before i managed to get
ADB working here. The USB debugging authorization popup was not showing no
matter what i did. Yes, i had USB debbuging on of course. Tried diferent
ADB drivers, etc. It only showed up when i had MobileGO running (?!).

Anyway the log is 10MB! I'm afraid it could have some personal details, is
there a way to pass this log to you privately?

**Comment by sansanca** [comment] 2015-07-19 02:44
Rovo, these guys are trying xposed in HTC M9+ (same chip Mediatek Helios
X10), is it supposed to take 1 hour optimizing stuff on the first run?

http://forum.xda-developers.com/one-m9/one-m9-general/howto-xposed-framework-alpha-odexed-rom-t3148901

**Comment by rovo89** [comment] 2015-07-21 19:42
You can use the contact form on repo.xposed.info. I usually delete support requests coming in from there, but it's ok for this case.

I don't remember how long it takes to recompile all the apps on my Nexus 5, but it's certainly a long time, around 15-20 minutes or so (with or without Xposed). It obviously also depends on the number and size of the installed apps. Hard to say where exactly the long compile time is coming from without detailed logs from the initial boot...

**Comment by sansanca** [comment] 2015-07-23 17:31
Ok Rovo, i replied via site feedback form.

**Comment by leloch** [comment] 2015-08-10 12:15
I have got the same bootloop issue with this phone, please let me know if you need any further troubleshooting or logs.

**Comment by rovo89** [comment] 2015-08-11 12:00
I have a rough idea what the problem is, but need more time for analysis.

**Comment by sansanca** [comment] 2015-08-11 17:49
Rovo, did you see my log? There is a new ROM for this phone and you
released new versions. Whatever you need, just warn us.

**Comment by rovo89** [comment] 2015-08-14 18:52
@sansanca Could you send me your /system/framework/arm/services.odex please?

**Comment by leloch** [comment] 2015-08-14 19:54
I uploaded the file here: https://drive.google.com/file/d/0B6eEmJ8k06xJOHRuWGhWdjRBTW8/view
It comes from the latest 18E ROM.

**Comment by rovo89** [comment] 2015-08-15 11:02
I'll close this in favor of #53, which has more crash information directly in the description. There's also a test version, please test. @sansanca @leloch.

**Closed by rovo89** 2015-08-15 11:02 UTC
Labels: more info needed
