### ISSUE TITLE
Yandex Maps cannot start after installing Xposed-v80-sdk23-arm64

### ISSUE THREAD

**Issue by larionov** [rovo89/Xposed#136] opened 2016-03-07 05:04 UTC
Application Yandex Maps (ru.yandex.yandexmaps) can not start with Xposed-v80-sdk23-arm64  installed. It shows splash screen and then crashes to the home screen.
Xposed doesn't have any modules installed right now, and when I uninstall xposed application works.

Logcat: http://pastebin.com/SxHjPNuu

I'm on a Nexus 6P Android 6.0.1 with TWRP 3.0.0

**Comment by rovo89** [comment] 2016-03-07 08:05
Duplicate of https://github.com/rovo89/android_art/issues/26
The logcat refers to a totally different, meanwhile fixed issue.

**Closed by rovo89** 2016-03-07 08:05 UTC

**Comment by larionov** [comment] 2016-03-07 08:20
I edited logcat after submitting the issue, looks like you refering to the original one. I'll post the correct link to the rovo89/android_art#26
