### ISSUE TITLE
Not working on mi 4c

### ISSUE THREAD

**Issue by AndropaX** [rovo89/Xposed#85] opened 2015-11-14 10:10 UTC
01-01 01:03:44.771 I/Xposed  (  445): -----------------
01-01 01:03:44.771 I/Xposed  (  445): Starting Xposed version 75, compiled for SDK 22
01-01 01:03:44.771 I/Xposed  (  445): Device: Mi-4c (Xiaomi), Android version 5.1.1 (SDK 22)
01-01 01:03:44.771 I/Xposed  (  445): ROM: LMY47V
01-01 01:03:44.771 I/Xposed  (  445): Build fingerprint: Xiaomi/libra/libra:5.1.1/LMY47V/5.11.12:user/release-keys
01-01 01:03:44.771 I/Xposed  (  445): Platform: arm64-v8a, 64-bit binary, system server: yes
01-01 01:03:44.771 I/Xposed  (  445): SELinux enabled: yes, enforcing: yes
01-01 01:03:44.811 I/Xposed  (  445): -----------------
01-01 01:03:44.811 I/Xposed  (  445): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
01-01 01:03:44.881 I/Xposed  (  445): Forcing image recompilation because /data/dalvik-cache/arm64/system@framework@boot.art is not compiled for the current Xposed version
01-01 01:03:54.801 I/Xposed  (  446): -----------------
01-01 01:03:54.801 I/Xposed  (  446): Starting Xposed version 75, compiled for SDK 22
01-01 01:03:54.801 I/Xposed  (  446): Device: Mi-4c (Xiaomi), Android version 5.1.1 (SDK 22)
01-01 01:03:54.801 I/Xposed  (  446): ROM: LMY47V
01-01 01:03:54.801 I/Xposed  (  446): Build fingerprint: Xiaomi/libra/libra:5.1.1/LMY47V/5.11.12:user/release-keys
01-01 01:03:54.801 I/Xposed  (  446): Platform: arm64-v8a, 32-bit binary, system server: no
01-01 01:03:54.801 I/Xposed  (  446): SELinux enabled: yes, enforcing: yes
01-01 01:03:54.801 I/Xposed  (  446): -----------------
01-01 01:03:54.801 I/Xposed  (  446): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
01-01 01:03:54.871 I/Xposed  (  446): Forcing image recompilation because /data/dalvik-cache/arm/system@framework@boot.art is not compiled for the current Xposed version
01-01 01:04:25.161 I/Xposed  (  445): Detected ART runtime
01-01 01:04:25.171 I/Xposed  (  445): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
01-01 01:04:25.221 E/Xposed  (  445): Error while loading XResources class 'android/content/res/XResources':
01-01 01:04:25.221 E/Xposed  (  445): java.lang.IncompatibleClassChangeError: android.content.res.XResources
01-01 01:04:25.221 E/Xposed  (  445):   at java.lang.Class dalvik.system.DexFile.defineClassNative(java.lang.String, java.lang.ClassLoader, long) (DexFile.java:-2)
01-01 01:04:25.221 E/Xposed  (  445):   at java.lang.Class dalvik.system.DexFile.defineClass(java.lang.String, java.lang.ClassLoader, long, java.util.List) (DexFile.java:226)
01-01 01:04:25.221 E/Xposed  (  445):   at java.lang.Class dalvik.system.DexFile.loadClassBinaryName(java.lang.String, java.lang.ClassLoader, java.util.List) (DexFile.java:219)
01-01 01:04:25.221 E/Xposed  (  445):   at java.lang.Class dalvik.system.DexPathList.findClass(java.lang.String, java.util.List) (DexPathList.java:321)
01-01 01:04:25.221 E/Xposed  (  445):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:54)
01-01 01:04:25.221 E/Xposed  (  445):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:511)
01-01 01:04:25.221 E/Xposed  (  445):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:469)
01-01 01:04:25.221 E/Xposed  (  445):   at boolean de.robv.android.xposed.XposedBridge.initNative() (XposedBridge.java:-2)
01-01 01:04:25.221 E/Xposed  (  445):   at void de.robv.android.xposed.XposedBridge.main(java.lang.String[]) (XposedBridge.java:96)
01-01 01:04:25.221 I/Xposed  (  445): Errors during native Xposed initialization
01-01 01:04:30.801 I/Xposed  (  446): Detected ART runtime
01-01 01:04:30.801 I/Xposed  (  446): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
01-01 01:04:30.851 E/Xposed  (  446): Error while loading XResources class 'android/content/res/XResources':
01-01 01:04:30.851 E/Xposed  (  446): java.lang.IncompatibleClassChangeError: android.content.res.XResources
01-01 01:04:30.851 E/Xposed  (  446):   at java.lang.Class dalvik.system.DexFile.defineClassNative(java.lang.String, java.lang.ClassLoader, long) (DexFile.java:-2)
01-01 01:04:30.851 E/Xposed  (  446):   at java.lang.Class dalvik.system.DexFile.defineClass(java.lang.String, java.lang.ClassLoader, long, java.util.List) (DexFile.java:226)
01-01 01:04:30.851 E/Xposed  (  446):   at java.lang.Class dalvik.system.DexFile.loadClassBinaryName(java.lang.String, java.lang.ClassLoader, java.util.List) (DexFile.java:219)
01-01 01:04:30.851 E/Xposed  (  446):   at java.lang.Class dalvik.system.DexPathList.findClass(java.lang.String, java.util.List) (DexPathList.java:321)
01-01 01:04:30.851 E/Xposed  (  446):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:54)
01-01 01:04:30.851 E/Xposed  (  446):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:511)
01-01 01:04:30.851 E/Xposed  (  446):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:469)
01-01 01:04:30.851 E/Xposed  (  446):   at boolean de.robv.android.xposed.XposedBridge.initNative() (XposedBridge.java:-2)
01-01 01:04:30.851 E/Xposed  (  446):   at void de.robv.android.xposed.XposedBridge.main(java.lang.String[]) (XposedBridge.java:96)
01-01 01:04:30.851 I/Xposed  (  446): Errors during native Xposed initialization

**Comment by rovo89** [comment] 2015-11-15 20:23
Probably a duplicate of https://github.com/rovo89/XposedBridge/issues/61

**Closed by rovo89** 2015-11-15 20:23 UTC
