### ISSUE TITLE
"unfortunately, nfc service has stopped" error message keeps pooping up after installing xposed framework

### ISSUE THREAD

**Issue by hao19** [rovo89/Xposed#113] opened 2016-01-16 16:30 UTC
When installing xposed framework on a nexus 6 with android 6.0.1, build mmb29s, there is a constant error message saying the nfc service has stopped and the message keeps on popping up repeatedly.

**Comment by rovo89** [comment] 2016-01-16 16:57
This is most likely a duplicate of https://github.com/rovo89/android_art/issues/28, which is also about failing compilation of the NfcService.

**Closed by rovo89** 2016-01-16 16:57 UTC
Labels: duplicate

**Comment by JayVx** [comment] 2016-02-08 21:08
same error on nexus 5x on latest marshmallow build
flashed twrp
rooted
install zip "xposed v80 arm64..."
loop on nfc error
