### ISSUE TITLE
Xposed appears to break some apps on CM13 @ Nexus 5.

### ISSUE THREAD

**Issue by tmp6154** [rovo89/Xposed#137] opened 2016-03-07 10:53 UTC
Xposed seems to add invalid jar reference that break some apps. I run CM13 on Nexus 5. For example, Yandex.Transport (https://play.google.com/store/apps/details?id=ru.yandex.yandexbus), Russian application for tracking public transport on map. Here's an example log from adb logcat. The /system/framework/tcmclient.jar doesn't exists. Re-flashing system, gapps but skipping Xposed causes app to work again, so that's definitely an issue with Xposed. Here's exerpt from log:

> 03-06 21:54:26.795 21868 21868 W System : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
> 03-06 21:54:26.829 21868 21868 W FlurryAgent: Start session
> 03-06 21:54:26.837 21868 21868 I YBus : Metrica event: map.appear. 
> 03-06 21:54:26.856 21868 21948 E yandex.maps: yandex::maps::runtime::async::internal::PackagedTaskCommon: 
> 03-06 21:54:26.859 21868 21950 E yandex.maps: yandex::maps::runtime::async::internal::PackagedTaskCommon: java.lang.StackOverflowError: stack size 1014KB
> -------— beginning of crash
> 03-06 21:54:26.862 21868 21878 F libc : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x20000 in tid 21878 (HeapTaskDaemon)

**Comment by rovo89** [comment] 2016-03-07 11:18
Duplicate of https://github.com/rovo89/android_art/issues/26
I don't know "tcmclient.jar" and I can't imagine any place where Xposed would add something to a classloader. Are you sure that this line doesn't exist without Xposed as well?

**Closed by rovo89** 2016-03-07 11:18 UTC
