### ISSUE TITLE
Bootloop Xperia M2

### ISSUE THREAD

**Issue by z0mbyHG** [rovo89/Xposed#131] opened 2016-02-27 18:17 UTC
After installing v80 sdk22 arm and rebooting device it hangs on bootloop.

02-27 18:59:14.483 I/Xposed  (  414): -----------------
02-27 18:59:14.483 I/Xposed  (  414): Starting Xposed version 80, compiled for SDK 22
02-27 18:59:14.483 I/Xposed  (  414): Device: D2303 (Sony), Android version 5.1.1 (SDK 22)
02-27 18:59:14.483 I/Xposed  (  414): ROM: 18.6.A.0.182
02-27 18:59:14.483 I/Xposed  (  414): Build fingerprint: Sony/D2303/D2303:5.1.1/18.6.A.0.182/1643041205:user/release-keys
02-27 18:59:14.483 I/Xposed  (  414): Platform: armeabi-v7a, 32-bit binary, system server: yes
02-27 18:59:14.483 I/Xposed  (  414): SELinux enabled: yes, enforcing: yes
02-27 18:59:18.280 I/Xposed  (  414): -----------------
02-27 18:59:18.280 I/Xposed  (  414): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
02-27 18:59:18.664 I/Xposed  (  414): Detected ART runtime
02-27 18:59:18.696 I/Xposed  (  414): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
02-27 18:59:19.017 E/Xposed  (  414): Cannot load any modules because /data/data/de.robv.android.xposed.installer/conf/modules.list was not found
02-27 18:59:20.275 F/libc    ( 1067): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x655aa6a8 in tid 1069 (Compiler driver)
02-27 18:59:20.275 F/libc    ( 1067): Fatal signal 11 (SIGSEGV), code 2, fault addr 0x50bc10e4 in tid 1070 (Compiler driver)
02-27 18:59:20.275 F/libc    ( 1067): Unable to open connection to debuggerd: Permission denied
02-27 18:59:20.377 F/libc    ( 1071): Fatal signal 6 (SIGABRT), code -6 in tid 1071 (main)
02-27 18:59:20.377 F/libc    ( 1071): Unable to open connection to debuggerd: Permission denied
02-27 18:59:20.431 F/libc    ( 1076): Fatal signal 11 (SIGSEGV), code 2, fault addr 0x75b9d6e4 in tid 1082 (Compiler driver)
02-27 18:59:20.431 F/libc    ( 1076): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xbc46fd88 in tid 1080 (Compiler driver)
02-27 18:59:20.432 F/libc    ( 1076): Unable to open connection to debuggerd: Permission denied

**Comment by rovo89** [comment] 2016-03-07 08:21
Another duplicate of #64

**Closed by rovo89** 2016-03-07 08:21 UTC
