### ISSUE TITLE
App freeze and crash

### ISSUE THREAD

**Issue by Eva850** [rovo89/Xposed#266] opened 2017-10-17 20:16 UTC
When Xposed is enabled and some modules are active, some apps freezes and crashes when launching. With Xposed disabled or all modules deactivated apps works. They works also when there are no more than 3 modules active.
Affected apps:
Messenger - com.facebook.orca
Media Re.scan - com.house.noranuko.mediarescanner
OS and Device:
Xperia Z5 Android 7.1
Systemless Xposed 88.1
Magisk
Logcat of Messenger crash:
[logcat.txt](https://github.com/rovo89/Xposed/files/1392474/logcat.txt)

**Comment by Droidphilev** [comment] 2017-10-18 18:43
Hi,

It seems i have kind of the same problem with 2 devices (Shamu 7.1.2 and Athene 7.0). After a while (most chance after a night of charge) apps start crashing. It are always the same apps. Uninstalling Xposed makes the crashing go away. Reflashing Xposed starts the problem again. All what helps is un/reinstalling the crashing apps. This goes well for some hours. The problems starts again. Not able to create a log now, i'm very sorry for this. I use the officials versions of Xposed.

**Comment by Eva850** [comment] 2017-10-18 19:19
Also for me re-installing those apps helps but only
for a while

**Comment by Droidphilev** [comment] 2017-10-19 12:27
Hi,

I think it is related to issue #234. At least: all the crashing apps are the ones that need internet. In my case: Google Docs, Telegram, Whatsapp, Aquamail, Google sheets and others.

**Comment by Eva850** [comment] 2017-10-19 18:57
It is probably device dependant, Telegram works fine for me. I had issue with Xposed on Marshmallow, some apps (Google translate, TugaBrowser, MobileMPK) could not detect internet connection after some time. Reboot helped but only for some time.

**Comment by Droidphilev** [comment] 2017-10-21 12:00
Hi,

Shortest fix that i could find for my 2 devices: boot, to recovery, flash uninstaller, flash installer, boot. This will last for a while (few hours).

**Comment by xdraylin** [comment] 2017-10-21 13:50
Wiping Cache + Dalvik does also help for some time.

**Comment by Droidphilev** [comment] 2017-10-21 13:51
Only wiping caches isn't enough in my case. :-(

**Comment by akorn** [comment] 2017-11-03 15:59
This is probably the same as #275; a different workaround was posted there, which is slightly less inconvenient.

**Comment by HankAviator** [comment] 2017-11-05 09:22
Happens to me for webview embed apps, e.g. WeChat, Chrome.
Intensive crashes can be soothed by clearing ART cache

**Comment by rovo89** [comment] 2017-12-18 08:30
Could you please try if it works better with v89?

**Comment by HankAviator** [comment] 2017-12-18 08:35
@rovo89 I've got two devices, one was OnePlus One, which I had to wipe ART cache quite often. Its 3GB RAM is not enough for daily use. I recently got a mi 6, and force closes have drastically decreased. 
On OnePlus One I had ARM Xposed, v88.2, LOS 14.1 nightly official; on Mi 6 I've got ARM64 Xposed, v88.2, LOS 14.1 unofficial; both are nougat.
Testing v89.

**Comment by Jedarc** [comment] 2017-12-18 11:57
I uninstalled Xposed and updated my LineageOS rom. Now my apps have stopped giving trouble.

**Comment by xdraylin** [comment] 2017-12-18 17:07
Also testing v89. Looks good so far. Will report back after a few days use.

**Comment by xdraylin** [comment] 2017-12-23 14:13
Not a single app crash since upgrading to v89. Seems like the problem is fixed now (at least for me).

**Comment by cokeboyle** [comment] 2017-12-23 14:24
Iam'cokeboyle

**Closed** 2017-12-28 11:19 UTC

**Comment by Joaquin25022001** [comment] 2018-04-14 05:44
2 of my games (Deemo and Cytus II) won't launch with Xposed framework v89 installed and activated. Uninstalling the framework solves this problem.
