### ISSUE TITLE
some fc on lg g4 h815 int

### ISSUE THREAD

**Issue by andigenn** [rovo89/Xposed#134] opened 2016-03-04 08:50 UTC
hi.
i have some fc on lg g4 h815 int marshmallow 6.0 v20e, with this message "com.android.phone was interrupted":
- apn list in settings --> mobile networks
- network in settings --> phone info
- status in settings --> phone info
- hardware info in settings --> phone info

i have successfully installed v80 sdk23 arm64

**Comment by rovo89** [comment] 2016-03-07 08:25
Try some fix, it might fix some FC.

No seriously, I always need logs to analyze issues. In this case though, it looks very much like a duplicate of the remaining issue in #100.

**Closed by rovo89** 2016-03-07 08:25 UTC
