### ISSUE TITLE
fail on HTC D820u Lolipop 5.0.2

### ISSUE THREAD

**Issue by MidoriYakumo** [rovo89/Xposed#97] opened 2015-12-08 13:38 UTC
```
I/SystemServiceManager(19961): Starting com.android.server.am.ActivityManagerService$Lifecycle
E/System  (19961): ******************************************
E/System  (19961): ************ Failure starting system services
E/System  (19961): java.lang.RuntimeException: Failed to create service com.android.server.am.ActivityManagerService$Lifecycle: service constructor threw an exception
E/System  (19961):      at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:100)
E/System  (19961):      at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:422)
E/System  (19961):      at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/System  (19961):      at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:675)
E/System  (19961):      at com.android.server.SystemServer.startBootstrapServices(<Xposed>)
E/System  (19961):      at com.android.server.SystemServer.run(SystemServer.java:316)
E/System  (19961):      at com.android.server.SystemServer.main(SystemServer.java:232)
E/System  (19961):      at java.lang.reflect.Method.invoke(Native Method)
E/System  (19961):      at java.lang.reflect.Method.invoke(Method.java:372)
E/System  (19961):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
E/System  (19961):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
E/System  (19961):      at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
E/System  (19961): Caused by: java.lang.reflect.InvocationTargetException
E/System  (19961):      at java.lang.reflect.Constructor.newInstance(Native Method)
E/System  (19961):      at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
E/System  (19961):      at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:89)
E/System  (19961):      ... 11 more
E/System  (19961): Caused by: java.lang.VerifyError: Rejecting class com.android.server.am.ActivityManagerService because it failed compile-time verification (declaration of 'com.android.server.am.ActivityManagerService' appears in /system/framework/services.jar)
E/System  (19961):      at com.android.server.am.ActivityManagerService$Lifecycle.<init>(ActivityManagerService.java:2368)
E/System  (19961):      ... 14 more
E/AndroidRuntime(19961): *** FATAL EXCEPTION IN SYSTEM PROCESS: main
E/AndroidRuntime(19961): java.lang.RuntimeException: Failed to create service com.android.server.am.ActivityManagerService$Lifecycle: service constructor threw an exception
E/AndroidRuntime(19961):        at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:100)
E/AndroidRuntime(19961):        at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:422)
E/AndroidRuntime(19961):        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime(19961):        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:675)
E/AndroidRuntime(19961):        at com.android.server.SystemServer.startBootstrapServices(<Xposed>)
E/AndroidRuntime(19961):        at com.android.server.SystemServer.run(SystemServer.java:316)
E/AndroidRuntime(19961):        at com.android.server.SystemServer.main(SystemServer.java:232)
E/AndroidRuntime(19961):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19961):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(19961):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
E/AndroidRuntime(19961):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
E/AndroidRuntime(19961):        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
E/AndroidRuntime(19961): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(19961):        at java.lang.reflect.Constructor.newInstance(Native Method)
E/AndroidRuntime(19961):        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
E/AndroidRuntime(19961):        at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:89)
E/AndroidRuntime(19961):        ... 11 more
E/AndroidRuntime(19961): Caused by: java.lang.VerifyError: Rejecting class com.android.server.am.ActivityManagerService because it failed compile-time verification (declaration of 'com.android.server.am.ActivityManagerService' appears in /system/framework/services.jar)
E/AndroidRuntime(19961):        at com.android.server.am.ActivityManagerService$Lifecycle.<init>(ActivityManagerService.java:2368)
E/AndroidRuntime(19961):        ... 14 more
E/AndroidRuntime(19961): Error reporting crash
E/AndroidRuntime(19961): java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.IActivityManager.handleApplicationCrash(android.os.IBinder, android.app.ApplicationErrorReport$CrashInfo)' on a null object reference
E/AndroidRuntime(19961):        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:118)
E/AndroidRuntime(19961):        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
E/AndroidRuntime(19961):        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
D/Process (19961): killProcess, pid=19961
D/Process (19961): com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException:138 java.lang.ThreadGroup.uncaughtException:693 java.lang.ThreadGroup.uncaughtException:690 
E/Zygote  (19811): Exit zygote because system server (-1246326784) has terminated
```

**Comment by MidoriYakumo** [comment] 2015-12-08 13:39
I am using xposed-v78-sdk21-arm64.zip

**Comment by rovo89** [comment] 2015-12-09 17:07
Probably a duplicate of #88.

**Closed by rovo89** 2015-12-09 17:07 UTC
Labels: duplicate

**Comment by henessy99** [comment] 2015-12-09 17:32
[root - init.zip](https://github.com/rovo89/Xposed/files/57100/root.-.init.zip)
i dont really know if these are the need files. i found theses in system(root)
