### ISSUE TITLE
Apps crashing on SDK25

### ISSUE THREAD

**Issue by MartinX3** [rovo89/Xposed#248] opened 2017-10-10 15:18 UTC
I use LineageOS 14.1 (Android 7.1) on my Nexus 6 64GB
After installing XPosed v88 and several restarts, first my build in browser (which uses the chrome engine updated over the play store) only has a white screen, not usable anymore.
Shortly after this bug, more and more apps are crashing on startup.

Running the uninstaller from 2016 resolved this problem.

PS: Thank you for your hard work.

**Comment by rovo89** [comment] 2017-10-10 15:28
Please post logs of the crashes. Also, please make sure that you have no modules activated, to ensure that really the framework is to blame.

**Comment by MartinX3** [comment] 2017-10-10 15:33
Thank you for your fast reply!

I'm installing xposed again, will disable every module and test it.

**Comment by Jedarc** [comment] 2017-10-11 11:40
I was having the same problem, but it was possibly being caused by some module, since I disabled everything and rebooted my phone, so the problems stopped.
For some reason (I believe not to be related to Exposed) some Facebook applications have not worked, maybe someone can be wrong thinking this.
I am also using LineageOS 14.1.

**Comment by rovo89** [comment] 2017-10-11 15:27
> For some reason (I believe not to be related to Exposed) some Facebook applications have not worked, maybe someone can be wrong thinking this.

I also had some Facebook/Messenger crashes yesterday after updating to v88.1 and soft rebooting. Those crashes were in libart.so, but it was called from Facebook's libdextricks.so - the name says it all. After a full reboot, the crashes were gone.

**Comment by Jedarc** [comment] 2017-10-11 17:40
Interestingly, I also did the upgrade to v88.1 and did the reboot, but unfortunately the problems continue with Facebook and related.

**Comment by MartinX3** [comment] 2017-10-12 13:17
But Facebook Lite and Messenger Lite are working fine.

**Comment by Jedarc** [comment] 2017-10-12 14:10
The lite versions of both are also working fine on my phone. But I would very much appreciate having no trouble using any other compatible application.

**Comment by C3C0** [comment] 2017-10-12 16:37
FYI. Running 88.1 on Op3T since it was released and so far no crash in either FB or Messenger

**Comment by MartinX3** [comment] 2017-10-13 13:14
Weird, running on v88.1 on my Nexus 7 tablet, the crashes occurred first, but went away after 2 full reboots. (No warm restart).

**Comment by rovo89** [comment] 2017-10-13 13:18
Which apps are we talking about now? Did you try without modules, could you please post logs?

**Comment by MartinX3** [comment] 2017-10-13 13:21
I own 2 devices
A Nexus 6 & a Nexus 7 (2013 Wifi)
On both devices there crashes occur, even background apps crashed.
But after 2 full reboots (cold restarts, not warm restarts), everything is now fine, without a crash.
Even with some modules which are updated for v88.x.

**Comment by rovo89** [comment] 2017-10-13 14:07
OK, so I'll close this issue. If it occurs again, please disable all modules, try again and post the logs.

**Closed by rovo89** 2017-10-13 14:07 UTC
