### ISSUE TITLE
V90-beta1 on Nexus 5x

### ISSUE THREAD

**Issue by Zell89** [rovo89/Xposed#308] opened 2018-01-09 12:49 UTC
The system is slow and laggish, the boot takes 2/3 minutes, tried the Unique Controls Halo module (probabily bad compatibility) and risulted in a bootloop, I had to re-flash the system because the unistaller had no effect. I'm on stock 8.1, with root and franco kernel.

**Comment by Zell89** [comment] 2018-01-09 16:02
[liveboot.log](https://github.com/rovo89/Xposed/files/1615721/liveboot.log)
[xposed_error_20180109_165837.log](https://github.com/rovo89/Xposed/files/1615722/xposed_error_20180109_165837.log)
Attached there are the boot log and the log from the xposed installer, the app is a bit instable and crashes always after a research in the download section, ask if more logs are needed.

**Comment by rovo89** [comment] 2018-01-09 16:38
Are you referring to the first boot? That will indeed take much longer as usual, but following boots should be pretty much as usual. Also it's not surprising the the system will respond slower right after installing Xposed. The compiled code for all apps will be invalidated. Android has a job which compiles apps which have been used, but it only runs once per night when the device is plugged in.

If you're willing to try it again, please flash again and try `adb shell cmd package bg-dexopt-job`, that will trigger compilation immediately (will run for a few minutes). Afterwards, please do a full reboot and see if it's better.

The crash in the installer app is known meanwhile as an incompatibility in a library I use: https://github.com/rovo89/XposedInstaller/issues/420

**Comment by rovo89** [comment] 2018-01-09 16:42
Actually, you might have to execute that as root, so
```
adb shell
su
cmd package bg-dexopt-job
```

**Comment by Zell89** [comment] 2018-01-09 17:15
Yes, it was the first boot, now boot time seems back to normal, sorry but I used Xposed last time few years ago and I didn't remember that first boot take longer than usual. The system run smooth after the second reboot but the applications startup sometimes is doubled (not sure it depends on Xposed). Regarding the module the bootloop can be a compatibility problem? Thanks.

**Comment by rrfeng** [comment] 2018-01-12 02:41
@rovo89 
I just installed v90beta1 by Xposed Installer, on my Pixel with 8.1 and Magisk root, 10 minutes has gone and still stuck in the boot...
If I force to reboot the phone, will there be any damage?

**Comment by rovo89** [comment] 2018-01-18 19:21
The command I mentioned above is now available in Xposed Installer.

Can't say anything about module compatiblity - Xposed APIs haven't change, except for the settings limitation I mentioned in my announcement. If the module developer analyzes the issue and thinks it's caused by the framework, they should open a new issue with the details for it.

I'm also using Pixel with 8.1 and Magisk root and it's working fine. Rebooting the devices shouldn't be a problem.

**Closed as completed by rovo89** 2018-01-18 19:21 UTC
