### ISSUE TITLE
Android not booting - HTC Desire 820

### ISSUE THREAD

**Issue by QkiZMR** [rovo89/Xposed#88] opened 2015-11-15 19:27 UTC
After installing Xposed on HTC Desire 820 with Lollipop system doesn't boot. It hangs right after kernel load. Logcat messages in attachment.
[logcat.txt](https://github.com/rovo89/Xposed/files/34976/logcat.txt)

**Comment by QkiZMR** [comment] 2015-11-16 19:31
Version xposed-v78-sdk21-arm64 still not working.
[logcat.txt](https://github.com/rovo89/Xposed/files/35875/logcat.txt)

**Comment by QkiZMR** [comment] 2015-11-17 17:56
After install Xposed from TWRP and clearing dalvik-cache same error.

**Comment by QkiZMR** [comment] 2015-11-19 14:04
Xposed log in attachment
[error.txt](https://github.com/rovo89/Xposed/files/38982/error.txt)

**Comment by rovo89** [comment] 2015-11-19 14:32
@QkiZMR Please be patient, I have a lot of other stuff to look at. I'll unlock this issue again once I found the time to look at your logs.

**Comment by rovo89** [comment] 2015-11-21 16:59
`1393                dex2oat  I  void com.android.server.am.ActivityStack.getTasksLocked(java.util.List, int, boolean) failed to verify: void com.android.server.am.ActivityStack.getTasksLocked(java.util.List, int, boolean): [0x3D] Cannot infer field from iget-object-quick`

This ROM seems to be extremely pre-optimized. Please upload these two files for further analysis:
/system/framework/arm64/boot.oat
/system/framework/arm64/services.odex

**Comment by QkiZMR** [comment] 2015-11-21 17:53
Here it is
https://owncloud.qkiz.pl/index.php/s/PcGiwLohscHGRB0
File are to big to upload on Github

**Comment by rovo89** [comment] 2015-11-29 20:30
Your ROM contains many instructions that have been optimized with loss of information that was available at compile time. I was able to reconstruct a few more of them, but some would be

**Comment by QkiZMR** [comment] 2015-12-01 18:27
It looks like it's working. Android booted up. Xposed installer see working framework
[logcat.txt](https://github.com/rovo89/Xposed/files/48882/logcat.txt)
![screenshot_2015-12-01-19-19-50](https://cloud.githubusercontent.com/assets/7574087/11509883/079415aa-9861-11e5-8ab1-dbc83bbb7a43.png)

[xposed_error_20151201_192457.txt](https://github.com/rovo89/Xposed/files/48886/xposed_error_20151201_192457.txt)

**Comment by Real-Vivacity** [comment] 2015-12-02 11:17
Phone gets stuck at boot animation after installing xposed. While the Xposed-v79-sdk21-arm64-test fixed the problem for some people i don't understand why it still bootloop for me. I wiped cache and everything but in vain.  

Someone else has the same problem and what we have in common is s-off and cid-11111111. Could this be related somehow? 


Additional info:
1. I have htc 820u dual sim running on lollipop.
2. bootloader unlocked
3. S-off
4. cid 11111111

**Comment by QkiZMR** [comment] 2015-12-02 11:24
Paste logs because Rovo isn't clairvoyant ;) After installing Xposed while system was booted up Android clears and regenerate art-cache by itself.

**Comment by Real-Vivacity** [comment] 2015-12-02 12:03
QkiZMR could you please shut up and mind your own business? that's the first time i post here how am i going to know i should post logs? If he asked me for it i would.

**Comment by Real-Vivacity** [comment] 2015-12-02 12:04
@rovo89  i will post a log asap.

**Comment by rovo89** [comment] 2015-12-02 12:17
@Real-Vivacity Calm down. Your reply was way more unfriendly than his hint. I'm actually glad when others point out beginners' mistakes, otherwise I would have even less time to work on issues.

**Comment by Real-Vivacity** [comment] 2015-12-02 13:10
@rovo89 my reply was right its not the first time this guy talked to me. I dont have to explain myself to you about that neither. If you wont check the log that's okay

**Comment by CaptainThrowback** [comment] 2015-12-02 13:18
It'd be nice if this could stay on topic and someone could just post a log? I'm looking at this issue with interest because I have an HTC device that also bootloops after installing Xposed. Every time I get an email notification hoping there's progress being made, I see nothing relevant (including this post). @rovo89 I have an S-OFF, unlocked HTC One A9 running stock odexed ROM. On both this device and the M9, Xposed would just loop at the boot animation after install. I'm running Marshmallow though, so none of the test versions you've posted so far apply to my device. Should I open a separate issue for this, or can you provide an arm64-sdk23 v79 zip here that I can test?

**Comment by QkiZMR** [comment] 2015-12-02 15:07
@Real-Vivacity I do not remember ever talked to you. First if you use Windows install Android drivers. If you are using Linux, you don't have to. Enable adb debugging in Android, connect phone to PC. Install ADB (http://lifehacker.com/the-easiest-way-to-install-androids-adb-and-fastboot-to-1586992378). After install Xposed, run on PC "adb logcat" in shell (cmd or powershell) and reboot phone. After some time that PC grab logs interrupt "adb logcat" command with CTRL+C, copy logs to file and post here.

**Comment by Real-Vivacity** [comment] 2015-12-02 15:18
@QkiZMR I already know how to do that thank you. @rovo89 here is the logcat. 
[logcat.txt](https://github.com/rovo89/Xposed/files/49855/logcat.txt)

**Comment by Kellwa** [comment] 2015-12-02 17:34
My HTC d820u not booting as well
There is my logcat
if you please can help @rovo89 
[logcat.txt](https://github.com/rovo89/Xposed/files/49994/logcat.txt)

**Comment by Kellwa** [comment] 2015-12-03 03:39
i found these lines in my logcat and i think they are related to the problem:

I/art     ( 1431): DexFile_isDexOptNeeded file /system/framework/arm64/services.odex needs to be recompiled with Xposed for /system/framework/services.jar

I/art     ( 1431): DexFile_isDexOptNeeded file /system/framework/arm64/usbnet.odex needs to be recompiled with Xposed for /system/framework/usbnet.jar

I/art     ( 1431): DexFile_isDexOptNeeded file /system/framework/arm64/ethernet-service.odex needs to be recompiled with Xposed for /system/framework/ethernet-service.jar

I/art     ( 1431): DexFile_isDexOptNeeded file /system/framework/arm64/wifi-service.odex needs to be recompiled with Xposed for /system/framework/wifi-service.jar

i uploaded the files mentioned in the above linesin case they are needed
https://drive.google.com/open?id=0B52LjwT71iQPN2licGhFMXBjYjA

**Comment by rovo89** [comment] 2015-12-03 14:24
The logs from @Real-Vivacity and @Kellwa and also @sprint-w in issue #95 point to the same issue: Class `com.htc.ub.HtcDeviceInfoManager` cannot be loaded, probably because `/system/framework/ub.jar` wasn't compiled before. This doesn't occur without Xposed because it will take the pre-compiled odex file. For further investigations, it would be great if any one of you could upload the whole `/system/framework` folder.

@CaptainThrowback Several issues that I have investigated and fixed since version 78 are interconnected. I have started porting some of them to Marshmallow, but I first want to get things right on Lollipop where I can get more test feedback. If you post a logcat, I can check it though, maybe it turns out to be an issue which should be fixed soon.

**Comment by sprint-w** [comment] 2015-12-03 14:54
@rovo89 I uploaded Framework of HTV31.
https://drive.google.com/open?id=0B-9X3itXmtpWVW8ySzFjSkgtOUE

**Comment by Real-Vivacity** [comment] 2015-12-03 14:58
@rovo89 here is the framework of htc 820u https://drive.google.com/file/d/0B_Mjq-6tzjOieVRVX2U2bVRidEk/view?usp=sharing

**Comment by QkiZMR** [comment] 2015-12-03 21:02
@rovo89 do you need my HTC 820n framework? For me v79test after few days of testing is working.

**Comment by CaptainThrowback** [comment] 2015-12-04 13:36
@rovo89 Here's the logcat from the failed boot on my HTC One A9 (Factory S-OFF, Unlocked):

https://www.dropbox.com/s/uo8h7nv8kear1cj/xposed-logcat-A9.txt?dl=0

**Comment by QkiZMR** [comment] 2015-12-04 14:14
Today I receive system update. New version of framework is in it. I will check if that update is compatible with v79test.

**Comment by rovo89** [comment] 2015-12-05 12:13
Thanks for the files, I'll look at them as soon as I find the time.

@CaptainThrowback Seems to be a different issue, but if you could upload your `/system/framework` as well, I can try to reproduce it myself.

**Comment by CaptainThrowback** [comment] 2015-12-05 17:00
@rovo89 I can't post my exact framework as I'm using a test version of a ROM I can't share, but this framework is from a release version for my device that should have the same issue:

https://www.dropbox.com/s/n2yb7a4f3uexmp3/framework.zip?dl=0

If you have any issues reproducing the issue, let me know and I can share my ROM's framework privately.

**Comment by henessy99** [comment] 2015-12-06 12:20
hello @rovo89 i got the same issue too, i have htc 820u dual sim. Can you tell us when you will check it approximately so that we can check back. sorry for asking i don't come online too often.

**Comment by fredweasleysr** [comment] 2015-12-06 19:16
@rovo89 thank you very much, my phone is HTC Desire 820u s-on China version.
I installed that test.zip with twrp, and it's booted, though it is still optimizing apps, I believe it will work just fine!
I can't say how thankful I am, I'm in China and I learn literature, I don't know a thing about Android development, I only know how to flash recoveries, boot and ROM,  I could never solve this problem on my own, it would take months before any solution show up on Chinese internet,
You know people like you made other people much more comfortable are the real society pillars.

**Comment by QkiZMR** [comment] 2015-12-07 22:15
System update to v2.10.401.4 appears few days ago with new Android framework. Xposed framework v79test still working :)

**Comment by henessy99** [comment] 2015-12-08 16:34
lots of waiting :( please @rovo89 are you going to check it soon?

**Comment by Real-Vivacity** [comment] 2015-12-09 11:36
patience @henessy99 i'm checking for any news everyday myself ;) i guess he got much work

**Comment by sprint-w** [comment] 2015-12-09 13:58
did @henessy99 donated it?

**Comment by rovo89** [comment] 2015-12-09 14:32
Yes, I'm indeed very busy, and constantly pinging me isn't exactly helpful.

Anyway, I have an idea what the problem could be. Could someone who is affected please upload their /init* files? I would like to check how the SYSTEMSERVERCLASSPATH is set, I assume it's missing /system/framework/ub.jar.

**Comment by QkiZMR** [comment] 2015-12-09 14:40
Version 79test is working for me. Variable SYSTEMSERVERCLASSPATH:
init.environ.rc:    export SYSTEMSERVERCLASSPATH /system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar:/system/framework/usbnet.jar

**Comment by henessy99** [comment] 2015-12-09 17:25
@rovo89 i would like to. but i don't know where these are stored. can anyone tell me please? i will upload these asap

**Comment by henessy99** [comment] 2015-12-09 17:33
[root - init.zip](https://github.com/rovo89/Xposed/files/57100/root.-.init.zip)
i dont really know if these are the needed files. i found these in system(root) @rovo89

**Comment by rovo89** [comment] 2015-12-09 18:30
Ok, let's give this a try. It adds /system/framework/ub.jar to SYSTEMSERVERCLASSPATH when Xposed is starting up:
https://www.dropbox.com/s/a3dx05jrcluzeop/xposed-v79-sdk21-arm64-test4.zip?dl=0

**Comment by Real-Vivacity** [comment] 2015-12-09 19:06
It took some time but finally boots, android is optimizing apps for the moment. i'll keep you updated but it should be good. thank you, you're awesome man respect. @rovo89

**Comment by QkiZMR** [comment] 2015-12-09 19:22
@rovo89 how to install new test version? Uninstall previous version then install this v79test4 or install overwriting previous version?

**Comment by rovo89** [comment] 2015-12-09 19:31
Unless explicietely stated otherwise, you can always flash new version over previous ones.

**Comment by Real-Vivacity** [comment] 2015-12-09 19:40
After flashing the latest version i cannot install any apps anymore. Weird. I'll try to look for a solution. Or if anyone has an idea that's welcome

**Comment by QkiZMR** [comment] 2015-12-09 20:30
New version is working well. I cant install apps too. I want to update FB app and it's fail. 
![screenshot_2015-12-09-21-26-00](https://cloud.githubusercontent.com/assets/7574087/11697810/cd077d58-9ebb-11e5-8b16-ef07d1521380.png)
[xposed_error_20151209_212138.txt](https://github.com/rovo89/Xposed/files/57313/xposed_error_20151209_212138.txt)
[logcat.txt](https://github.com/rovo89/Xposed/files/57314/logcat.txt)

**Comment by Kellwa** [comment] 2015-12-09 22:37
Thanks
v79test4 is working
But can't install new apps
These are my init files
[init.zip](https://github.com/rovo89/Xposed/files/57430/init.zip)
One old apk i have did got installed is called BlueVPN
Thats it if it give any help
[BlueVPN 2.5.zip](https://github.com/rovo89/Xposed/files/57432/BlueVPN.2.5.zip)

**Comment by Real-Vivacity** [comment] 2015-12-10 03:08
And one more thing playstore dissapeared lol 😄

**Comment by MidoriYakumo** [comment] 2015-12-10 10:35
great， test1 works for my China version D820u, test4 can merely install few apps (maybe 32bit?)

**Comment by sprint-w** [comment] 2015-12-11 01:28
It does not work yet on my Butterfly3.

[1211.txt](https://github.com/rovo89/Xposed/files/58939/1211.txt)

**Comment by Kellwa** [comment] 2015-12-11 04:03
Anyone know if we can go around app installing error using XInstaller module?

**Comment by Real-Vivacity** [comment] 2015-12-11 04:37
@Kellwa i tried to look for a solution but nothing. :/ and some of my apps stopped working. i guess we'll have to wait for @rovo89 to check it. i bet he'll find a quick fix. maybe we should upload a logcat meanwhile

**Comment by Kellwa** [comment] 2015-12-11 05:34
@Real-Vivacity 
you are right
but another bug i think is every time i reboot "Android is upgrading" shows up and optimize some apps
that;s my xposed log file
the last 33 line showed up when trying to install an app
[xposed_error_20151211_071151.txt](https://github.com/rovo89/Xposed/files/59054/xposed_error_20151211_071151.txt)

**Comment by QkiZMR** [comment] 2015-12-11 12:10
Last 33 lines is a segfault, not install an app. That means that dex2oat command crashed.

**Comment by rovo89** [comment] 2015-12-11 12:24
This all seems to come down to the same thing. App installation triggers dex2oat, and if an app couldn't be compiled, Android will also trigger dex2oat again on the next reboot. I can reproduce this on 5.0, but not 5.1, so I have to see what the root cause it. Unfortunately, such an analysis can easily consume many hours, even if the fix might be very small. I'll see if I can find a solution on the weekend, but I'm not sure.

**Comment by Kellwa** [comment] 2015-12-11 13:59
Ok @rovo89
I really thank you for your help
Hope that i can donate you but these cridet card money and electric money not very supported in my country
Thank you alot man

**Comment by Real-Vivacity** [comment] 2015-12-11 14:30
Thank you thats cool, be waiting. And im willing to donate for the great work. I'll check that asap ;)

**Comment by Real-Vivacity** [comment] 2015-12-12 13:11
Thank you thats cool, be waiting. And im willing to donate for the great work. I'll check that asap ;) @rovo89 our version of android is 5.0.2

**Comment by rovo89** [comment] 2015-12-13 20:48
I think I found a commit which fixes the issues with the compilation of some apps, please test this: https://www.dropbox.com/s/il42y2jg1khsrm4/xposed-v79-sdk21-arm64-test5.zip?dl=0

**Comment by Real-Vivacity** [comment] 2015-12-14 11:33
Testing seems to be working. :)

**Comment by Kellwa** [comment] 2015-12-14 13:27
It's working smoothly and no bugs so far
Thanks alot man

**Comment by MidoriYakumo** [comment] 2015-12-14 13:36
if test1 is perfect for me should I try test5 :)

**Comment by Real-Vivacity** [comment] 2015-12-14 15:17
lol @MidoriYakumo why should you? he just fixed the bugs that prevented test1 from working on our htc 820u.

**Comment by rovo89** [comment] 2015-12-14 17:36
@MidoriYakumo Yes, it would be helpful because test5 has more changes than test1 and this might again break something that has worked before (like test4 fixed one issue, but caused another one). Please clear the Dalvik cache to ensure that the ROM is recompiled completely.

**Comment by QkiZMR** [comment] 2015-12-15 20:43
It seems that everything is working. No errors in Xposed logs and no errors related to Xposed in logcat.
[error.txt](https://github.com/rovo89/Xposed/files/63164/error.txt)
[logcat.txt](https://github.com/rovo89/Xposed/files/63165/logcat.txt)

**Comment by rovo89** [comment] 2015-12-16 21:32
@CaptainThrowback Could you please test this? https://www.dropbox.com/s/9ulioa3tacwmns2/xposed-v79-sdk23-arm64-test5.zip?dl=0

**Comment by CaptainThrowback** [comment] 2015-12-16 23:30
@rovo89 Test5 appears to be working on my A9! Thanks for working on this! Would you like a log of bootup?

**Comment by sprint-w** [comment] 2015-12-17 12:36
@revo89 Thank you.It worked.

[1217.txt](https://github.com/rovo89/Xposed/files/65352/1217.txt)

**Comment by rovo89** [comment] 2015-12-17 21:20
Thanks for all the testing. Now I published the official version 79 and I recommend that you flash it over the test version. To be on the safe side, I would also recommend to clear the Dalvik cache once again.

**Closed by rovo89** 2015-12-17 21:20 UTC

**Comment by rovo89** [comment] 2016-04-29 10:48
I think the specific fix I made in https://github.com/rovo89/Xposed/commit/e4142329d6b1b99e38f4b412629d60712327b5e6 is no longer necessary now due to the changes I have done in v83 (which lets the system use the odex file in interpret-only mode even when it couldn't be recompiled). Therefore, I would like to revert it.

Could you please help me to verify that Xposed still works afterwards on your HTC device?
https://www.dropbox.com/sh/9loai8trb1zwouq/AADWTy5KKMz5q3p1e19z71JBa?dl=0
Please clear the Dalvik cache after flashing the ZIP. If the system still boots afterwards, I think all should be fine. Please also mention your device and Android version.

**Comment by sprint-w** [comment] 2016-04-30 01:14
I flashed v84-sdk21-arm64-test2 and clear cache and dalvik cache.
It worked fine.

HTC J butterfly3(HTV31)
Android 5.0.2

**Comment by rovo89** [comment] 2016-04-30 07:16
Great, thanks for confirming! Further tests (especially on other Android versions) are of course welcome.

**Comment by QkiZMR** [comment] 2016-05-01 13:42
I'll try it today and give feedback.

**Comment by QkiZMR** [comment] 2016-05-01 19:37
It seems to work. Xposed log. No errors:
```
05-01 20:45:06.310 I/Xposed  (  457): -----------------
05-01 20:45:06.310 I/Xposed  (  457): Starting Xposed version 84-test2, compiled for SDK 21
05-01 20:45:06.310 I/Xposed  (  457): Device: HTC Desire 820 (HTC), Android version 5.0.2 (SDK 21)
05-01 20:45:06.310 I/Xposed  (  457): ROM: LRX22G release-keys
05-01 20:45:06.310 I/Xposed  (  457): Build fingerprint: htc/a51ul_htc_europe/htc_a51ul:5.0.2/LRX22G/630093.4:user/release-keys
05-01 20:45:06.310 I/Xposed  (  457): Platform: arm64-v8a, 64-bit binary, system server: yes
05-01 20:45:06.310 I/Xposed  (  457): SELinux enabled: yes, enforcing: yes
05-01 20:45:07.320 I/Xposed  (  457): -----------------
05-01 20:45:07.330 I/Xposed  (  457): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
05-01 20:45:15.600 I/Xposed  (  459): -----------------
05-01 20:45:15.600 I/Xposed  (  459): Starting Xposed version 84-test2, compiled for SDK 21
05-01 20:45:15.600 I/Xposed  (  459): Device: HTC Desire 820 (HTC), Android version 5.0.2 (SDK 21)
05-01 20:45:15.600 I/Xposed  (  459): ROM: LRX22G release-keys
05-01 20:45:15.600 I/Xposed  (  459): Build fingerprint: htc/a51ul_htc_europe/htc_a51ul:5.0.2/LRX22G/630093.4:user/release-keys
05-01 20:45:15.600 I/Xposed  (  459): Platform: arm64-v8a, 32-bit binary, system server: no
05-01 20:45:15.600 I/Xposed  (  459): SELinux enabled: yes, enforcing: yes
05-01 20:45:15.610 I/Xposed  (  459): -----------------
05-01 20:45:15.610 I/Xposed  (  459): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
05-01 20:46:13.030 I/Xposed  (  457): Detected ART runtime
05-01 20:46:13.030 I/Xposed  (  457): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
05-01 20:46:14.230 I/Xposed  (  457): Loading modules from /data/app/ds.cpuoverlay-1/base.apk
05-01 20:46:16.780 I/Xposed  (  457):   Loading class ds.cpuoverlay.xposed.XposedHooks
05-01 20:46:16.790 I/Xposed  (  457): Loading modules from /data/app/tw.fatminmin.xposed.minminguard-1/base.apk
05-01 20:46:16.790 I/Xposed  (  457):   File does not exist
05-01 20:46:16.800 I/Xposed  (  457): Loading modules from /data/app/at.jclehner.appopsxposed-1/base.apk
05-01 20:46:19.350 I/Xposed  (  457):   Loading class at.jclehner.appopsxposed.AppOpsXposed
05-01 20:46:19.360 I/Xposed  (  457): Loading modules from /data/app/de.defim.apk.bootmanager-1/base.apk
05-01 20:46:19.800 I/Xposed  (  457):   Loading class de.defim.apk.bootmanager.Xposed
05-01 20:46:19.800 I/Xposed  (  457):     [BootManager] initialized
05-01 20:46:19.800 I/Xposed  (  457):   Loading class de.defim.apk.bootmanager.Xcheck
05-01 20:46:19.800 I/Xposed  (  457): Loading modules from /data/app/ma.wanam.youtubeadaway-1/base.apk
05-01 20:46:19.920 I/Xposed  (  457):   Loading class ma.wanam.youtubeadaway.Xposed
05-01 20:46:19.920 I/Xposed  (  457): Loading modules from /data/app/com.germainz.activityforcenewtask-1/base.apk
05-01 20:46:20.030 I/Xposed  (  457):   Loading class com.germainz.activityforcenewtask.XposedMod
05-01 20:46:20.050 I/Xposed  (  457): Loading modules from /data/app/com.oasisfeng.greenify-1/base.apk
05-01 20:46:21.800 I/Xposed  (  459): Detected ART runtime
05-01 20:46:21.890 I/Xposed  (  459): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
05-01 20:46:22.170 I/Xposed  (  459): Loading modules from /data/app/ds.cpuoverlay-1/base.apk
05-01 20:46:24.500 I/Xposed  (  459):   Loading class ds.cpuoverlay.xposed.XposedHooks
05-01 20:46:24.510 I/Xposed  (  459): Loading modules from /data/app/tw.fatminmin.xposed.minminguard-1/base.apk
05-01 20:46:24.510 I/Xposed  (  459):   File does not exist
05-01 20:46:24.510 I/Xposed  (  459): Loading modules from /data/app/at.jclehner.appopsxposed-1/base.apk
05-01 20:46:26.680 I/Xposed  (  459):   Loading class at.jclehner.appopsxposed.AppOpsXposed
05-01 20:46:26.690 I/Xposed  (  459): Loading modules from /data/app/de.defim.apk.bootmanager-1/base.apk
05-01 20:46:27.040 I/Xposed  (  457):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
05-01 20:46:27.060 I/Xposed  (  457):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
05-01 20:46:27.060 I/Xposed  (  457): Loading modules from /data/app/com.voidvapps.intelli3g-1/base.apk
05-01 20:46:27.100 I/Xposed  (  459):   Loading class de.defim.apk.bootmanager.Xposed
05-01 20:46:27.110 I/Xposed  (  459):     [BootManager] initialized
05-01 20:46:27.110 I/Xposed  (  459):   Loading class de.defim.apk.bootmanager.Xcheck
05-01 20:46:27.110 I/Xposed  (  459): Loading modules from /data/app/ma.wanam.youtubeadaway-1/base.apk
05-01 20:46:27.190 I/Xposed  (  459):   Loading class ma.wanam.youtubeadaway.Xposed
05-01 20:46:27.190 I/Xposed  (  459): Loading modules from /data/app/com.germainz.activityforcenewtask-1/base.apk
05-01 20:46:27.290 I/Xposed  (  459):   Loading class com.germainz.activityforcenewtask.XposedMod
05-01 20:46:27.290 I/Xposed  (  459): Loading modules from /data/app/com.oasisfeng.greenify-1/base.apk
05-01 20:46:29.190 I/Xposed  (  457):   Loading class com.voidvapps.intelli3g.Xposed3GHook
05-01 20:46:33.150 I/Xposed  (  459):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
05-01 20:46:33.170 I/Xposed  (  459):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
05-01 20:46:33.170 I/Xposed  (  459): Loading modules from /data/app/com.voidvapps.intelli3g-1/base.apk
05-01 20:46:34.830 I/Xposed  (  459):   Loading class com.voidvapps.intelli3g.Xposed3GHook
05-01 20:46:43.520 I/Xposed  ( 1496): CoolTool: hook permissions stuff
05-01 21:32:25.760 I/Xposed  ( 5054): CoolTool: hook statusbar stuff
05-01 21:32:25.820 I/Xposed  ( 5054): CoolTool: Hook layouts
05-01 21:32:35.480 I/Xposed  ( 5054): CoolTool: clock in the icon area
05-01 21:32:48.200 I/Xposed  ( 6220):   HTC: [OK]
05-01 21:32:48.300 I/Xposed  ( 5054): CoolTool: addNotificationViews: pkg=android; id=17040622; iconId=17303127; ongoing=true
05-01 21:32:59.930 I/Xposed  ( 5054): CoolTool: addNotificationViews: pkg=com.android.settings; id=2130837752; iconId=2130837752; ongoing=true
05-01 21:34:32.741 I/Xposed  ( 7520):   HTC: [OK]
05-01 21:34:46.411 I/Xposed  ( 1496): CoolTool: Hook layouts
05-01 21:34:49.041 I/XposedInstaller( 7894): Downloaded http://dl.xposed.info/repo/full.xml.gz with status 0 (error: null), size 983539 bytes
05-01 21:34:55.831 I/XposedInstaller( 7894): Updated repository http://dl.xposed.info/repo/full.xml.gz to version 8175 (860 new / 0 removed modules)
05-01 21:35:02.701 I/Xposed  ( 5054): CoolTool: addNotificationViews: pkg=android; id=17039584; iconId=17301642; ongoing=false
```

**Comment by QkiZMR** [comment] 2016-05-03 13:06
Maybe this is stupid but when I flashed test 84 version I got pops and cracks when listen music, no matter what player I'm using. After reflash v83 everything back to normal.

**Comment by sprint-w** [comment] 2016-05-09 16:30
LINE crushed when open picture select window.(attach)
