### ISSUE TITLE
Bootloop on LG G4 (H815) Stock MM

### ISSUE THREAD

**Issue by schreda** [rovo89/Xposed#100] opened 2015-12-17 22:00 UTC
Getting bootloop with v79 on  LG G4 running Android 6.0

edit: can't run adb logcat because no device is found on boot process

**Comment by rovo89** [comment] 2015-12-17 23:06
Sorry, but I really can't help you without logs. Usually, adb will indeed not be working immediately, but it should pick after a minute or two. If it doesn't work even after a few minutes, you can try to look for a tool called LiveBoot, but I haven't tried that myself.

Also, did Xposed work in earlier versions?

**Comment by schreda** [comment] 2015-12-18 00:06
Got it!

Here is the log i got. I hope its enough. Don't know where the loop starts
[logcat.txt](https://github.com/rovo89/Xposed/files/66076/logcat.txt)

**Comment by romracer** [comment] 2015-12-18 17:33
Looks related to rovo89/XposedBridge@dc21651

**Comment by rovo89** [comment] 2015-12-20 19:25
Yes, probably. So we'll probably need something like 01c324454bb0e7eba82ae56895b04fb571ba5073 also for Marshmallow. I'm glad that I always put that many details into the commit message, that will hopefully help to reproduce the issue locally and find a way to fix it (the affected code has been refactored, so a new hook will be needed).

**Comment by orhtun01** [comment] 2015-12-22 10:28
I could not generate the logcat during boot. But i guess the same issue. Screenshot taken during bootloop using liveboot. Lg G4 MM 6.0 xposed v79.

http://tinypic.com/r/qoyrms/9

**Comment by orhtun01** [comment] 2015-12-23 13:28
Some additional notes on top of my previous report + screenshots.
It always bootloops when i invoke a direct reboot from  the system.
It sometimes does not bootloop when i shotdown and restart.
If it bootloops, the only way to get out is to take the battery off, press the power button for a few seconds. Put the battery in and restart.

I hope all these helps.
Thanks.

**Comment by danregev** [comment] 2015-12-26 17:29
Same problem, even when uninstalled xposed and xposed installer before

**Comment by Catfriend1** [comment] 2016-01-07 16:15
I also tried KDZ v20 MM on LG G4. Got a bootloop when removing GMSCore and captured this. Maybe it is the same issue what happens when modifying another system part by XPosed install.

[2016-01-07_logcat_bootbloop.zip](https://github.com/rovo89/Xposed/files/81366/2016-01-07_logcat_bootbloop.zip)

**Comment by Catfriend1** [comment] 2016-01-19 17:34
Solution: Flash deodexed apps into 815H 20B Android 6 Stock ROM via TWRP. Install v79-sdk23-arm64 XPosed Framework. This works. Got this from another site.

**Comment by rovo89** [comment] 2016-01-20 21:10
@Catfriend1 I would say that's a workaround, not a solution. ;)

Here's an attempt to actually fix this issue: https://www.dropbox.com/s/8lddtv03riu8a1r/xposed-v80-sdk23-arm64-test2.zip?dl=0

**Comment by Catfriend1** [comment] 2016-01-20 22:29
Thanks I'll try this the next days and report if it works.

**Comment by Catfriend1** [comment] 2016-01-20 22:41
Cool, it works. Many thanks *thumbs up*

**Comment by sector1979** [comment] 2016-01-26 15:27
@rovo89 now it boot correctly on last 20D for LG G4, but Home and Wheather stock apps always crash

**Comment by Lupus-Dei** [comment] 2016-01-31 16:46
Accessing Hardware Information in Settings/General/About Phone/Hardware-Information results in FC of com.android.phone.
[dmesg.txt](https://github.com/rovo89/Xposed/files/111361/dmesg.txt)
[logcat.txt](https://github.com/rovo89/Xposed/files/111360/logcat.txt)

**Comment by suljo94** [comment] 2016-01-31 18:56
@rovo89 could you make a simular zip for arm(32 bits) bec ause you said the lg g3 has the same problem but it isnt 64 bit

**Comment by rovo89** [comment] 2016-02-01 19:44
> Works. But after flashing V80-arm64-test2, Accessing Hardware Information in Settings/General/About Phone/Hardware-Information results in FC of com.android.phone.

Can anyone else confirm this? Please also test this without any enabled modules.

> could you make a simular zip for arm(32 bits) bec ause you said the lg g3 has the same problem but it isnt 64 bit (sdk 23)

Thanks, but I don't think it needs to be tested separately. Please wait for the official version to be released.

**Comment by ciro73** [comment] 2016-02-01 19:57
> Works. But after flashing V80-arm64-test2, Accessing Hardware Information in Settings/General/About Phone/Hardware-Information results in FC of com.android.phone.>

confirmed. same here. LG G4 H815 MM with V80-arm64-test2
module disabled (got only one enabled) but still FC on com.android,phone

**Comment by Lupus-Dei** [comment] 2016-02-01 21:24
I can only confirm that com.android.phone is still FC'ing after disabling **all** modules.

**Comment by danregev** [comment] 2016-02-02 05:54
I also noticed that h815 reboots repeatedly using Life360 app (Family Locator). I use Rooted MM 20a and Xposed v80 test2

**Comment by Lupus-Dei** [comment] 2016-02-02 16:27
Have to correct myself. It's not only FC'ing while accessing Hardware Info but **also** when trying to access "Network" and "Status". @ciro73 Can you confirm?

**Comment by ciro73** [comment] 2016-02-02 17:26
yes confirmed. will FC also on network and status

**Comment by rovo89** [comment] 2016-02-02 17:30
@danregev Please open a separate issue for that.

@Lupus-Dei / @ciro73 OK, acknowledged. It would be good to see if the devices attempts to compile this app while booting. You should be able to get a log by execution "adb logcat -v time > logcat.txt" in one shell and then "adb shell stop;start" in another one. Press Ctrl+C in the first shell once the devices has booted.

Also, the logs contain some crashes for weather-related APKs. Could someone please upload /system/app/LGWeatherService?

**Comment by HorstiG** [comment] 2016-02-02 17:34
LG G4 H815, Genisys ROM 27.01 20d, SuperSU 2.67, TWRP 2.8.7.0, Imperium Kernel v1.6
Xposed 2.80 beta2. 130 Apps and 16 Modules. 
No crashes, but the phone runs **very** choppy

Same Xposed Configuration on S5 G900F. S5 runs like clockwork.

**Comment by Lupus-Dei** [comment] 2016-02-02 17:36
I'm back on a deodexed build and can't provide logs until this weekend. Sorry.
@HorstiG You need to provide logs.

**Comment by rovo89** [comment] 2016-02-02 17:38
> You need to provide logs.

No, I won't look at this when 16 modules are enabled. Disable all of them and try again. Also, I need a more detailed description what's slow and yes, probably I'll also need logs that somehow document this.

**Comment by HorstiG** [comment] 2016-02-02 17:38
@Lupus-Dei There is no LOG for a poor running phone.

**Comment by HorstiG** [comment] 2016-02-02 17:45
I have only the Log File from Xposed Installer, Hope that helps a little.
https://www.dropbox.com/s/dzor7ukie0ovga3/error.log?dl=0

**Comment by ciro73** [comment] 2016-02-02 17:52
i will try to do this and provide the logs later today. got only one module running

Am 2. Februar 2016 18:30:44 MEZ, schrieb rovo89 <notifications@github.com>:

**Comment by rovo89** [comment] 2016-02-02 17:55
> I have only the Log File from Xposed Installer, Hope that helps a little.
> https://www.dropbox.com/s/dzor7ukie0ovga3/error.log?dl=0

As I said: I can't support you. The log is full of errors from incompatible modules, and also from "/sbin/rctd". Disable everything and reboot, maybe that already helps.

**Comment by HorstiG** [comment] 2016-02-02 18:04
@rovo89 I have the same problems, without modules,or I'm too spoiled by Samsung.
A 64-bit Handy with 3GB Ram should fly. 
I am totally disappointed. That was my first and last LG.

**Comment by HorstiG** [comment] 2016-02-02 18:07
@rovo89 Thank you for your Answer.

**Comment by ciro73** [comment] 2016-02-02 19:16
@rovo89 not sure if this still needed as the issue seems to be closed but here we go...
[logcat.txt and LGW...apk](http://www.file-upload.net/download-11272190/logcat_LGWeather.tgz.html)
let me know if this is what you asked for

**Comment by rovo89** [comment] 2016-02-02 19:48
Sorry, it got closed by a commit.

Regarding the weather app: Is there only this APK? I had expected a directory, most likely with an odex file.

**Comment by ciro73** [comment] 2016-02-02 19:52
@rovo89 ups => http://www.file-upload.net/download-11272341/LGWeatherService.tgz.html

**Comment by smpranto** [comment] 2016-02-09 15:19
Sir,
I am using Symphony Helio S1, MT6753, 64 bit,  ARM_V8, mali T-720, Android-5.1.1.
I have ROOTED my device, installed Busibox. Flashed Xposed_framework v80_sdk22_arm64.Zip via TWRP recovery. I have been made restart my device after every flashed and apk installed.
But, latest xposed installer always say me, Framework installed but not active.
I was checked the config folder the is no disabled log file.
Plz help me. plz modify a xposed for my device.

Easy Links....
1. Screen Shots images of Error:

https://drive.google.com/file/d/0B3-Ulhgr85EUQkpCbHZNa2ZReUU/view?usp=docslist_api

https://drive.google.com/file/d/0B3-Ulhgr85EURnJfRWdWbnNwYzQ/view?usp=docslist_api

https://drive.google.com/file/d/0B3-Ulhgr85EUU3FZVmZUX1czbzA/view?usp=docslist_api
----------------------------
2. Error Log files:

https://drive.google.com/file/d/0B3-Ulhgr85EUaENqcWw1ODJPSUE/view?usp=docslist_api

https://drive.google.com/file/d/0B3-Ulhgr85EUT1dmZHhMZE9fcWs/view?usp=docslist_api

Please sir, help me. I know that i am disturbing you. But, you are one and only genius developer.
Sorry to disturbed you.

Email: proashbabu@gmail.com
Facebook: www.facebook.com/left.away

**Comment by speed47** [comment] 2016-03-14 19:27
As a workaround for these crashes (weather and some tabs in "about phone"), I did manage to extract the apk versions packaged with a custom-built rom for the G4 (advertised to be Xposed-compatible), and pushed it to my device (running the stock LG MM rom). The main difference I can tell is that these working versions are deoxeded (there's only the apk in /system/priv-app).

An excerpt of the logcat of the weather crash was:

> Caused by: java.lang.ClassNotFoundException: Didn't find class "com.lge.sizechangable.weather.platform.provider.WeatherPlatformProvider" on path: DexPathList[...]
> 	Suppressed: java.io.IOException: No original dex files found for dex location /system/app/LGWeatherService/LGWeatherService.apk 

The logcat is similar for the remaining issues, namely the hardware info tab in "about phone":

> Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.settings.lge.DeviceInfoLgePhoneIdentity" on path: DexPathList[...]
>        Suppressed: java.io.IOException: Failed to open dex files from /system/priv-app/LGSettings/LGSettings.apk

And the "network" tab in "about phone":

> Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.settings.lge.DeviceInfoLgeNetwork" on path: DexPathList[...]
>         Suppressed: java.io.IOException: Failed to open dex files from /system/priv-app/LGSettings/LGSettings.apk

All these are fixed by using the two deodexed apks. Maybe the odexed versions are LG-encrypted or something ?

More complete logcats and original apks available on request :)

**Comment by rovo89** [comment] 2016-04-20 06:43
At anyone else who is running a stock ROM on an LG device: I recently made some changes which might affect your device. To ensure that Xposed still works, I'd like to have some testers.

For those who want to test: https://www.dropbox.com/sh/gketc1pry8ovy33/AACEqJME6LijmlFzrRlkAnwja?dl=0
There are two test zips for every Android version/platform combination. Please first flash test1, clear the Dalvik cache and reboot. There might be a boot loop, but please give it at least 10 minutes. Then please repeat the exact same procedure with test2. Please report here which device and ROM you're using and whether versions test1 and/or test2 worked for you. Thanks!

**Comment by sweeneyuk** [comment] 2016-04-20 09:36
Test 2 solves the issues with the crashes. Using stock LG sw MM 6.0

**Comment by rovo89** [comment] 2016-04-20 10:18
@sweeneyuk Did you also try test1?

**Comment by sweeneyuk** [comment] 2016-04-20 10:39
Yes it bootlooped for 15mins

**Comment by Lupus-Dei** [comment] 2016-04-20 10:43
test1 results in continuous bootloop. Waited a solid 15 minutes, then rebooted to recovery. test2 boot up fine and seems to have solved all the System Settings related crashes. LGWeather is still FC'ing though. I'll put logs asap.

**Comment by rovo89** [comment] 2016-04-27 17:07
Fixed in v83. For the weather app crashes, I assume that the files are protected somehow. Please continue here: https://github.com/rovo89/Xposed/issues/125

**Closed by rovo89** 2016-04-27 17:07 UTC
Labels: incompatibility
