### ISSUE TITLE
NFC-Service keeps chrashing

### ISSUE THREAD

**Issue by Modzon** [rovo89/Xposed#128] opened 2016-02-09 13:25 UTC
When I've flashed xposed and I reboot, when my phone has booted up my phone keeps saying:
Unfortunately, Nfc Service has stopped
Unfortunately, Trebuchet has stopped.
Unfortunately, Profiles trust has stopped.
Unfortunately, Gallery has stopped.
Unfortunately, CM Bug Report has been stopped.
The rom I'd use is Cyanogenmod 13 for LG L70 D320n.

**Comment by scarline** [comment] 2016-02-27 15:44
Hey, I have the same issue with a brand new Nexus 6p.

    Flashed MMB29Q
    Flashed TRWP Recovery 3.0.0 angler
    Installed SuperSU BETA-SuperSU-v2.67-20160121175247 (all fine until here)
    Flashed xposed-v80-sdk23-arm64.zip ---> Get NFC Loop (after reboot gap services random FC)

I also tried:
1. Flashed MMB29Q
2. Flashed TRWP Recovery 3.0.0 angler
3. Installed SuperSU BETA-SuperSU-v2.67-20160121175247
4. Installed XposedInstaller_3.0_alpha4.apk (all fine until here)
5. Flashed xposed-v80-sdk23-arm64.zip

---> Get NFC Loop (after reboot gap services random FC)

Changed SuperSu to multiuser-support, thrust for systemlevel applications and activation during boot in the options had NO effect.

I did hear that flashing xposed > do factory reset, cleaning data > install xposed installer > flash SuperSU could be a possible way that works. Does anyone have experience on this? Does it make a difference when the reboot is done by the xposed-installer?

Many people have his issue, so it must be related to the more recent versions. Is there a confirmation that v78 is working better and without FC for NFC and gaps? Is there a workaround? I would like to install xprivacy....

**Comment by hao19** [comment] 2016-03-03 23:32
same issue with the nexus 6, android 6.0.1, build MMB29Q

**Comment by watchmakerful** [comment] 2016-03-06 00:05
Same issue with all versions of Xposed on ODEXed 6.0.1 ROMs. it does not occur on a deodexed ROM (Chroma).

**Comment by rovo89** [comment] 2016-03-07 08:27
Duplicate of https://github.com/rovo89/android_art/issues/28

**Closed by rovo89** 2016-03-07 08:27 UTC
